import * as SecureStore from "expo-secure-store";
import {
    createContext,
    useCallback,
    useContext,
    useEffect,
    useMemo,
    useState,
    type ReactNode,
} from "react";
import { Platform } from "react-native";

export type NookLanguage = "en" | "zu" | "fr" | "ts";

const STORAGE_KEY = "nook_language";

const translations: Record<NookLanguage, Record<string, string>> = {
    en: {},
    zu: {
        "Home": "Ikhaya",
        "Explore": "Hlola",
        "Messages": "Imilayezo",
        "Profile": "Iphrofayela",
        "Settings": "Izilungiselelo",
        "Account": "I-akhawunti",
        "Preferences": "Okuncamelayo",
        "Privacy & security": "Ubumfihlo nokuphepha",
        "Your activity": "Okwenzayo",
        "Biometric app lock": "Ukukhiya uhlelo ngeminwe noma ubuso",
        "Remember presence sign-in": "Khumbula ukungena kobukhona",
        "Keeps Nook presence sign-in saved on this device between app launches.": "Igcina ukungena kobukhona be-Nook kule divayisi phakathi kokuvula uhlelo.",
        "Unable to load sign-in preference": "Ayikwazanga ukulayisha ukukhetha kokungena",
        "Could not update sign-in preference": "Ayikwazanga ukubuyekeza ukukhetha kokungena",
        "Protect your nook": "Vikela i-nook yakho",
        "Would you like to turn on biometric unlock to help keep your account private?": "Ungathanda ukuvula ukuqinisekisa ngobuso noma ngeminwe ukuze uvikele i-akhawunti yakho?",
        "Turn on biometric lock": "Vula ukukhiya ngobuso noma ngeminwe",
        "Not now": "Hhayi manje",
        "Biometrics unavailable": "Ukuqinisekisa ngobuso noma ngeminwe akutholakali",
        "Set up Face ID or fingerprint unlock in your device settings first.": "Qala ngokusetha i-Face ID noma ukuvula ngeminwe kuzilungiselelo zedivayisi yakho.",
        "Could not update biometric app lock": "Ayikwazanga ukubuyekeza ukukhiya kohlelo",
        "Biometric authentication failed. Please try again.": "Ukuqinisekisa ngobuso noma ngeminwe kuhlulekile. Zama futhi.",
        "Set up Face ID or fingerprint unlock on your device first.": "Qala ngokusetha i-Face ID noma ukuvula ngeminwe kudivayisi yakho.",
        "Biometric app lock is available only on a supported mobile device.": "Ukukhiya ngeminwe noma ngobuso kutholakala kuphela kudivayisi yeselula esekelwayo.",
        "Enable biometric app lock": "Vumela ukukhiya kohlelo ngeminwe noma ngobuso",
        "Disable biometric app lock": "Khubaza ukukhiya kohlelo ngeminwe noma ngobuso",
        "Unlock nook": "Vula i-nook",
        "Nook is locked": "I-nook ikhiyiwe",
        "Verify your identity to continue.": "Qinisekisa ukuthi nguwe ukuze uqhubeke.",
        "Unlock with biometrics": "Vula ngeminwe noma ngobuso",
        "Verifying…": "Kuyaqinisekiswa…",
        "Checking…": "Kuyahlolwa…",
        "On": "Kuvuliwe",
        "Off": "Kuvaliwe",
        "Unavailable": "Akutholakali",
        "Support & Legal": "Usizo Nezomthetho",
        "Help & support": "Usizo nokwesekwa",
        "Edit profile": "Hlela iphrofayela",
        "Saved posts": "Okuthunyelwe okulondoloziwe",
        "Blocked users": "Abantu abavinjiwe",
        "Report a problem": "Bika inkinga",
        "Privacy Policy": "Inqubomgomo Yobumfihlo",
        "Terms of Service": "Imigomo Yesevisi",
        "About": "Mayelana",
        "Share feedback": "Yabelana ngempendulo",
        "Sign Out": "Phuma",
        "Signing out…": "Kuyaphunywa…",
        "Language": "Ulimi",
        "Choose the language used in nook.": "Khetha ulimi olusetshenziswa ku-nook.",
        "English": "IsiNgisi",
        "isiZulu": "isiZulu",
        "Cancel": "Khansela",
        "Save": "Londoloza",
        "Done": "Kwenziwe",
        "Retry": "Zama futhi",
        "Loading…": "Kuyalayishwa…",
        "Search": "Sesha",
        "Search people": "Sesha abantu",
        "Search posts": "Sesha okuthunyelwe",
        "Follow": "Landela",
        "Following": "Uyalandela",
        "Followers": "Abalandeli",
        "Unfollow": "Yeka ukulandela",
        "Message": "Thumela umlayezo",
        "Post": "Okuthunyelwe",
        "Posts": "Okuthunyelwe",
        "Videos": "Amavidiyo",
        "Saved": "Kulondoloziwe",
        "Like": "Thanda",
        "Unlike": "Yeka ukuthanda",
        "Comment": "Beka amazwana",
        "Comments": "Amazwana",
        "Reply": "Phendula",
        "Replies": "Izimpendulo",
        "Share": "Yabelana",
        "Edit": "Hlela",
        "Delete": "Susa",
        "Write a comment…": "Bhala amazwana…",
        "Write a reply…": "Bhala impendulo…",
        "Send": "Thumela",
        "Send message": "Thumela umlayezo",
        "Type a message…": "Bhala umlayezo…",
        "Online": "Kuxhunyiwe",
        "Offline": "Akuxhunyiwe",
        "New message": "Umlayezo omusha",
        "No messages yet.": "Akukabi namilayezo.",
        "No videos to show.": "Awekho amavidiyo azoboniswa.",
        "No blocked users": "Abekho abantu abavinjiwe",
        "Unblock": "Vulela",
        "Unblocking…": "Kuyavulwa…",
        "Block user": "Vimba umuntu",
        "Block": "Vimba",
        "Profile unavailable": "Iphrofayela ayitholakali",
        "Create story": "Dala indaba",
        "Your story": "Indaba yakho",
        "Story viewers": "Ababukele indaba",
        "Pause": "Misa isikhashana",
        "Resume": "Qhubeka",
        "Share your feedback": "Yabelana ngempendulo yakho",
        "What’s on your mind?": "Ucabangani?",
        "Send feedback": "Thumela impendulo",
        "Name (optional)": "Igama (akuphoqelekile)",
        "Email (optional)": "I-imeyili (akuphoqelekile)",
        "Thanks for helping improve nook!": "Siyabonga ngokusiza ukuthuthukisa i-nook!",
        "Edit Profile": "Hlela Iphrofayela",
        "Discover people": "Thola abantu",
        "Back to profile": "Buyela kuphrofayela",
        "Back to settings": "Buyela kuzilungiselelo",
        "No saved posts yet.": "Akukabi nalokhu okuthunyelwe okulondoloziwe.",
        "When people follow this profile, they’ll appear here.": "Uma abantu belandela le phrofayela, bazovela lapha.",
        "The profiles they follow will appear here.": "Amaphrofayela abawalandelayo azovela lapha.",
        "Load more": "Layisha okwengeziwe",
        "Couldn’t load. Tap to retry.": "Ayikwazanga ukulayisha. Thepha ukuze uzame futhi.",
        "Something went wrong. Check your connection and try again.": "Kukhona okungahambanga kahle. Hlola uxhumano lwakho bese uzama futhi.",
        "You’ve blocked this account. Unblock them to see their posts and interact again.": "Uvimbile le akhawunti. Yivulele ukuze ubone okuthunyelwe kwayo futhi uxhumane nayo.",
        "No one here yet.": "Akekho okwamanje.",
        "Tap to resume": "Thepha ukuze uqhubeke",
        "Edit story": "Hlela indaba",
        "Delete story": "Susa indaba",
        "Keep story": "Gcina indaba",
        "Story unavailable": "Indaba ayitholakali",
        "This story is no longer available.": "Le ndaba ayisatholakali.",
        "What would you like to share?": "Yini ongathanda ukuyabelana ngayo?",
        "Add a caption…": "Faka amazwibela…",
        "Publish": "Shicilela",
        "Publishing…": "Kuyashicilelwa…",
        "Discard": "Lahla",
        "Discard changes?": "Lahla izinguquko?",
        "Edit post": "Hlela okuthunyelwe",
        "Save changes": "Londoloza izinguquko",
        "Saving…": "Kuyalondolozwa…",
        "Could not load your profile": "Ayikwazanga ukulayisha iphrofayela yakho",
        "Your profile": "Iphrofayela yakho",
        "Username": "Igama lomsebenzisi",
        "Name": "Igama",
        "Bio": "Mayelana nawe",
        "Website": "Iwebhusayithi",
        "Location": "Indawo",
        "Photo": "Isithombe",
        "Camera": "Ikhamera",
        "No conversations yet.": "Akukabi nezingxoxo.",
        "Message requests": "Izicelo zemilayezo",
        "Accept": "Yamukela",
        "Decline": "Yenqaba",
        "Today": "Namuhla",
        "Yesterday": "Izolo",
        "Active now": "Uyasebenza manje",
        "Last seen": "Ugcinwe ukubonakala",
        "Unknown": "Akwaziwa",
        "Search nook": "Sesha ku-nook",
        "People": "Abantu",
        "For you": "Okwakho",
        "Recent": "Okwakamuva",
        "Clear": "Sula",
        "No results found.": "Ayikho imiphumela etholakele.",
        "Signed in as": "Ungene ngemvume njengo",
        "Could not change language": "Ulimi alukwazanga ukushintshwa",
        "Please try again.": "Sicela uzame futhi.",
        "Preview account": "I-akhawunti yokubuka kuqala",
        "Sign out is available from your live profile.": "Ungaphuma kuphrofayela yakho yangempela.",
        "Unable to sign out": "Ayikwazanga ukuphuma",
        "Unable to open email": "Ayikwazanga ukuvula i-imeyili",
        "Unable to open link": "Ayikwazanga ukuvula isixhumanisi",
        "Edit your profile photo": "Hlela isithombe sakho sephrofayela",
        "Go back": "Buyela emuva",
        "Tagged": "Okumakiwe",
        "Try again": "Zama futhi",
        "Could not unblock user": "Ayikwazanga ukuvulela lo muntu",
        "Couldn’t load your blocked users.": "Ayikwazanga ukulayisha abantu obavimbile.",
        "People you block will appear here. You can unblock them at any time.": "Abantu obavimbayo bazovela lapha. Ungabavulela noma nini.",
        "Unblock user": "Vulela umuntu",
        "Unblock @": "Vulela @",
        "Continue": "Qhubeka",
        "Group messaging": "Imilayezo yeqembu",
        "Conversation unavailable": "Ingxoxo ayitholakali",
        "Back to messages": "Buyela emilayezweni",
        "Your feed starts here": "Okuphakelayo kwakho kuqala lapha",
        "Explore the community": "Hlola umphakathi",
        "story": "indaba",
        "post": "okuthunyelwe",
        "Keep this screen open while your": "Gcina lesi sikrini sivuliwe ngenkathi",
        "is being shared.": "kwabiwa.",
        "Write a caption…": "Bhala amazwibela…",
        "Share story": "Yabelana ngendaba",
        "Send a link to this story": "Thumela isixhumanisi sale ndaba",
        "Remove it before it expires": "Isuse ngaphambi kokuba iphelelwe isikhathi",
        "Post unavailable": "Okuthunyelwe akutholakali",
        "Media unavailable. Tap to retry.": "Imidiya ayitholakali. Thepha ukuze uzame futhi.",
        "Search people, posts, or topics...": "Sesha abantu, okuthunyelwe noma izihloko...",
        "Search name or username": "Sesha igama noma igama lomsebenzisi",
        "Load earlier messages": "Layisha imilayezo emidala",
        "Could not load reactions": "Ayikwazanga ukulayisha ukusabela",
        "Could not update message request": "Ayikwazanga ukubuyekeza isicelo somlayezo",
        "Could not react to message": "Ayikwazanga ukusabela kumlayezo",
        "Could not edit message": "Ayikwazanga ukuhlela umlayezo",
        "Could not delete message": "Ayikwazanga ukususa umlayezo",
        "Could not open chat": "Ayikwazanga ukuvula ingxoxo",
        "Could not update like": "Ayikwazanga ukubuyekeza ukuthanda",
        "Could not update follow": "Ayikwazanga ukubuyekeza ukulandela",
        "Create a post": "Dala okuthunyelwe",
        "Edited": "Kuhleliwe",
        "Sending…": "Kuyathunyelwa…",
        "Delivered": "Kulethiwe",
        "You": "Wena",
        "Dismiss reactions": "Vala ukusabela",
        "Message options": "Izinketho zomlayezo",
        "This message will be removed only from your chat.": "Lo myalezo uzosuswa engxoxweni yakho kuphela.",
        "This message will be removed for everyone in the conversation.": "Lo myalezo uzosuswa kuwo wonke umuntu engxoxweni.",
        "Close message options": "Vala izinketho zomlayezo",
        "Delete message?": "Susa umlayezo?",
        "React with": "Phendula ngo",
        "Remove": "Susa",
        "Cancel editing": "Khansela ukuhlela",
        "Cancel reply": "Khansela impendulo",
        "Decline message request": "Yenqaba isicelo somlayezo",
        "Accept message request": "Yamukela isicelo somlayezo",
        "Open emoji picker": "Vula ukukhetha ama-emoji",
        "No conversations yet": "Akukabi nezingxoxo",
        "Retry sharing": "Zama ukwabelana futhi",
        "Opening conversation…": "Kuvulwa ingxoxo…",
        "Couldn’t open conversation": "Ayikwazanga ukuvula ingxoxo",
        "Check your connection and try again.": "Hlola uxhumano lwakho bese uzama futhi.",
        "Search members to message": "Sesha amalungu ongawathumelela umlayezo",
        "Cancel block confirmation": "Khansela ukuqinisekiswa kokuvimba",
        "They won’t be able to see your posts or message you. You won’t see their posts, and you’ll both be unfollowed.": "Ngeke bakwazi ukubona okuthunyelwe kwakho noma bakuthumele umlayezo. Ngeke ubone okuthunyelwe kwabo, futhi nizoyeka ukulandelana nobabili.",
        "Blocking…": "Kuyavinjwa…",
        "Saving your profile": "Iphrofayela yakho iyalondolozwa",
        "Saving": "Kuyalondolozwa",
        "Close reaction details": "Vala imininingwane yokusabela",
        "Could not share": "Ayikwazanga ukwabelana",
        "Could not save bookmark": "Ayikwazanga ukulondoloza ibhukhimakhi",
        "Could not delete comment": "Ayikwazanga ukususa amazwana",
        "Could not save profile": "Ayikwazanga ukulondoloza iphrofayela",
        "Could not update": "Ayikwazanga ukubuyekeza",
        "Check your profile": "Hlola iphrofayela yakho",
        "Your unsaved profile changes will be lost.": "Izinguquko zephrofayela yakho ezingalondoloziwe zizolahleka.",
        "Keep editing": "Qhubeka nokuhlela",
        "Choose a JPG or PNG": "Khetha i-JPG noma i-PNG",
        "Please select a JPG or PNG image for your profile photo.": "Sicela ukhethe isithombe se-JPG noma se-PNG sesithombe sakho sephrofayela.",
        "Choose a smaller photo": "Khetha isithombe esincane",
        "Select an image with a known size of 5 MB or less.": "Khetha isithombe esinosayizi owaziwayo ongu-5 MB noma ngaphansi.",
        "Unable to open photos": "Ayikwazanga ukuvula izithombe",
        "Please try opening the photo library again.": "Sicela uzame ukuvula ilabhulali yezithombe futhi.",
        "Choose a username": "Khetha igama lomsebenzisi",
        "Your name": "Igama lakho",
        "Tell people about yourself": "Tshela abantu ngawe",
        "City, country": "Idolobha, izwe",
        "Save profile": "Londoloza iphrofayela",
        "Change profile photo": "Shintsha isithombe sephrofayela",
        "Change Photo": "Shintsha isithombe",
        "JPG, PNG up to 5MB": "JPG, PNG kufika ku-5MB",
        "This is how people find you on nook.": "Yile ndlela abantu abakuthola ngayo ku-nook.",
        "Display Name": "Igama eliboniswa emphakathini",
        "This is your public name.": "Leli igama lakho elibonwa umphakathi.",
        "Share your first moment, or discover people to follow.": "Yabelana ngomzuzu wakho wokuqala, noma uthole abantu ongabalandela.",
        "Unread": "Engafundiwe",
        "Groups": "Amaqembu",
        "For now, start a private conversation with one member.": "Okwamanje, qala ingxoxo eyimfihlo nelungu elilodwa.",
        "You’re all caught up": "Usufinyelele emilayezweni yakamuva",
        "You don’t have any unread messages.": "Awunayo imilayezo engafundiwe.",
        "Start a conversation with someone in the community.": "Qala ingxoxo nomuntu othile emphakathini.",
        "We couldn’t open this conversation. Check your connection and that you’re signed in with the right account.": "Asikwazanga ukuvula le ngxoxo. Hlola uxhumano lwakho nokuthi ungene nge-akhawunti efanele.",
        "Search Explore": "Sesha ku-Hlola",
        "No posts found. Try another search or topic.": "Akukho okuthunyelwe okutholakele. Zama olunye usesho noma isihloko.",
        "Search people, posts, or topics": "Sesha abantu, okuthunyelwe noma izihloko",
        "Suggested for you": "Okuphakanyiselwe wena",
        "See all suggested people": "Bona bonke abantu abaphakanyisiwe",
        "See all": "Bona konke",
        "No suggested people yet.": "Abekho abantu abaphakanyisiwe okwamanje.",
        "Choose a topic": "Khetha isihloko",
        "Open": "Vula",
        "View": "Buka",
        "Options for": "Izinketho ze-",
        "topic": "isihloko",
        "All": "Konke",
        "Travel": "Ukuhamba",
        "Nature": "Imvelo",
        "Pets": "Izilwane ezifuywayo",
        "Food": "Ukudla",
        "Design": "Idizayini",
        "Lifestyle": "Indlela yokuphila",
        "Open post": "Vula okuthunyelwe",
        "Post options": "Izinketho zokuthunyelwe",
        "Unlike post": "Yeka ukuthanda okuthunyelwe",
        "Like post": "Thanda okuthunyelwe",
        "View comments": "Buka amazwana",
        "Add your story": "Engeza indaba yakho",
        "Story": "Indaba",
        "More story options": "Ezinye izinketho zendaba",
        "Previous story": "Indaba edlule",
        "Next story": "Indaba elandelayo",
        "Finishing publication": "Kuqedelwa ukushicilela",
        "Keep this screen open while the server confirms your": "Gcina lesi sikrini sivuliwe ngenkathi iseva iqinisekisa",
        "Cancel upload?": "Khansela ukulayisha?",
        "Your unfinished upload will be discarded.": "Ukulayisha kwakho okungakaqedwa kuzolahlwa.",
        "Your unfinished upload and caption will be discarded.": "Ukulayisha kwakho okungakaqedwa namazwibela kuzolahlwa.",
        "Keep uploading": "Qhubeka nokulayisha",
        "Cancel upload": "Khansela ukulayisha",
        "Discard story?": "Lahla indaba?",
        "Discard post?": "Lahla okuthunyelwe?",
        "Your selected photo will be discarded.": "Isithombe osikhethile sizolahlwa.",
        "Your selected media and caption will be discarded.": "Imidiya namazwibela okukhethile kuzolahlwa.",
        "Your text post will be discarded.": "Okuthunyelwe kwakho kombhalo kuzolahlwa.",
        "Close composer": "Vala umhleli wokuthunyelwe",
        "New story": "Indaba entsha",
        "New post": "Okuthunyelwe okusha",
        "Share post": "Yabelana ngokuthunyelwe",
        "Posting…": "Kuyathunyelwa…",
        "Select a photo for your story": "Khetha isithombe sendaba yakho",
        "Select a photo for your post": "Khetha isithombe sokuthunyelwe kwakho",
        "Change media": "Shintsha imidiya",
        "Add media": "Engeza imidiya",
        "Media": "Imidiya",
        "Opening…": "Kuyavulwa…",
        "Change selected media": "Shintsha imidiya ekhethiwe",
        "sec": "isekhondi",
        "Post caption": "Amazwibela okuthunyelwe",
        "Uploading": "Kuyalayishwa",
        "Preparing media…": "Kulungiselelwa imidiya…",
        "Delete post?": "Susa lokhu okuthunyelwe?",
        "Send a link to this post": "Thumela isixhumanisi salokhu okuthunyelwe",
        "Remove this post": "Susa lokhu okuthunyelwe",
        "Search people and posts": "Sesha abantu nokuthunyelwe",
        "Close": "Vala",
        "Close post options": "Vala izinketho zokuthunyelwe",
        "This removes the post, its media, likes, and comments.": "Lokhu kususa okuthunyelwe, imidiya yako, ukuthandwa namazwana.",
        "OK": "KULUNGILE",
        "Shares a link that opens this post in nook": "Yabelana ngesixhumanisi esivula lokhu okuthunyelwe ku-nook",
        "Delete comment?": "Susa amazwana?",
        "This comment and its replies will no longer be visible.": "La mazwana nezimpendulo zawo ngeke zisabonakala.",
        "This post may have been deleted.": "Kungenzeka ukuthi lokhu okuthunyelwe kususiwe.",
        "Close story viewers": "Vala ababukeli bendaba",
        "Close story options": "Vala izinketho zendaba",
        "Cancel deleting story": "Khansela ukususa indaba",
        "Dismiss message": "Vala umlayezo",
        "Version": "Inguqulo",
        "Welcome": "Siyakwamukela",
        "Sign in to continue to your account and pick up where you left off.": "Ngena ngemvume ukuze uqhubekele ku-akhawunti yakho futhi uqhubeke lapho ugcine khona.",
        "Signing in…": "Kuyangena ngemvume…",
        "By continuing, you agree to our": "Ngokuqhubeka, uyavumelana ne-",
        "and acknowledge our": "futhi uyavuma",
        "Completing sign in": "Kuqedelwa ukungena ngemvume",
        "Nook": "Nook",
        "Finishing sign in": "Kuqedelwa ukungena ngemvume",
        "Getting things ready": "Kulungiselelwa konke",
        "Your account is being connected securely. This will only take a moment.": "I-akhawunti yakho ixhunywa ngokuphephile. Lokhu kuzothatha isikhashana.",
        "Signing in": "Kuyangena ngemvume",
        "Secure sign-in": "Ukungena ngemvume okuphephile",
        "Newest first": "Okusha kuqala",
        "Oldest first": "Okudala kuqala",
        "Sort comments": "Hlunga amazwana",
        "Newest": "Okusha",
        "Oldest": "Okudala",
        "Close sort menu": "Vala imenyu yokuhlunga",
        "Comment options": "Izinketho zamazwana",
        "Edit or delete your comment": "Hlela noma susa amazwana akho",
        "Close comment options": "Vala izinketho zamazwana",
        "Edit comment": "Hlela amazwana",
        "Delete comment": "Susa amazwana",
        "Unlike comment": "Yeka ukuthanda amazwana",
        "Like comment": "Thanda amazwana",
        "Couldn’t load saved posts. Tap Saved again to retry.": "Ayikwazanga ukulayisha okuthunyelwe okulondoloziwe. Thepha Okulondoloziwe ukuze uzame futhi.",
        "Tagged posts are not available yet.": "Okumakiwe akukatholakali.",
        "No videos from": "Awekho amavidiyo avela ku-",
        "yet.": "okwamanje.",
        "No posts yet. Your moments will appear here.": "Akukabi nalokhu okuthunyelwe. Izikhathi zakho zizovela lapha.",
        "No posts yet.": "Akukabi nalokhu okuthunyelwe.",
        "hasn’t shared any moments.": "akabelananga ngezikhathi okwamanje.",
        "This profile isn’t available.": "Le phrofayela ayitholakali.",
        "No followers yet": "Akukabi nabalandeli",
        "Not following anyone yet": "Akalandeli muntu okwamanje",
        "User": "Umsebenzisi",
    },
    fr: {
        "Home": "Accueil",
        "Explore": "Explorer",
        "Messages": "Messages",
        "Profile": "Profil",
        "Settings": "Paramètres",
        "Account": "Compte",
        "Preferences": "Préférences",
        "Privacy & security": "Confidentialité et sécurité",
        "Your activity": "Votre activité",
        "Biometric app lock": "Verrouillage biométrique de l’application",
        "Remember presence sign-in": "Mémoriser la connexion de présence",
        "Keeps Nook presence sign-in saved on this device between app launches.": "Conserve la connexion de présence de Nook sur cet appareil entre les ouvertures de l’application.",
        "Unable to load sign-in preference": "Impossible de charger la préférence de connexion",
        "Could not update sign-in preference": "Impossible de modifier la préférence de connexion",
        "Protect your nook": "Protégez votre nook",
        "Would you like to turn on biometric unlock to help keep your account private?": "Souhaitez-vous activer le déverrouillage biométrique pour protéger votre compte ?",
        "Turn on biometric lock": "Activer le verrouillage biométrique",
        "Not now": "Pas maintenant",
        "Biometrics unavailable": "Biométrie indisponible",
        "Set up Face ID or fingerprint unlock in your device settings first.": "Configurez d’abord Face ID ou le déverrouillage par empreinte dans les réglages de votre appareil.",
        "Could not update biometric app lock": "Impossible de modifier le verrouillage biométrique",
        "Biometric authentication failed. Please try again.": "L’authentification biométrique a échoué. Réessayez.",
        "Set up Face ID or fingerprint unlock on your device first.": "Configurez d’abord Face ID ou le déverrouillage par empreinte sur votre appareil.",
        "Biometric app lock is available only on a supported mobile device.": "Le verrouillage biométrique est disponible uniquement sur un appareil mobile compatible.",
        "Enable biometric app lock": "Activer le verrouillage biométrique",
        "Disable biometric app lock": "Désactiver le verrouillage biométrique",
        "Unlock nook": "Déverrouiller nook",
        "Nook is locked": "Nook est verrouillé",
        "Verify your identity to continue.": "Confirmez votre identité pour continuer.",
        "Unlock with biometrics": "Déverrouiller avec la biométrie",
        "Verifying…": "Vérification…",
        "Checking…": "Vérification…",
        "On": "Activé",
        "Off": "Désactivé",
        "Unavailable": "Indisponible",
        "Support & Legal": "Aide et informations légales",
        "Help & support": "Aide et assistance",
        "Edit profile": "Modifier le profil",
        "Saved posts": "Publications enregistrées",
        "Blocked users": "Utilisateurs bloqués",
        "Report a problem": "Signaler un problème",
        "Privacy Policy": "Politique de confidentialité",
        "Terms of Service": "Conditions d’utilisation",
        "About": "À propos",
        "Share feedback": "Envoyer un commentaire",
        "Sign Out": "Se déconnecter",
        "Signing out…": "Déconnexion…",
        "Language": "Langue",
        "Choose the language used in nook.": "Choisissez la langue utilisée dans nook.",
        "English": "Anglais",
        "isiZulu": "isiZulu",
        "Cancel": "Annuler",
        "Save": "Enregistrer",
        "Done": "Terminé",
        "Retry": "Réessayer",
        "Loading…": "Chargement…",
        "Search": "Rechercher",
        "Search people": "Rechercher des personnes",
        "Search posts": "Rechercher des publications",
        "Follow": "Suivre",
        "Following": "Abonné(e)",
        "Followers": "Abonnés",
        "Unfollow": "Ne plus suivre",
        "Message": "Message",
        "Post": "Publication",
        "Posts": "Publications",
        "Videos": "Vidéos",
        "Saved": "Enregistré",
        "Like": "J’aime",
        "Unlike": "Je n’aime plus",
        "Comment": "Commenter",
        "Comments": "Commentaires",
        "Reply": "Répondre",
        "Replies": "Réponses",
        "Share": "Partager",
        "Edit": "Modifier",
        "Delete": "Supprimer",
        "Write a comment…": "Écrire un commentaire…",
        "Write a reply…": "Écrire une réponse…",
        "Send": "Envoyer",
        "Send message": "Envoyer un message",
        "Type a message…": "Écrire un message…",
        "Online": "En ligne",
        "Offline": "Hors ligne",
        "New message": "Nouveau message",
        "No messages yet.": "Aucun message pour le moment.",
        "No videos to show.": "Aucune vidéo à afficher.",
        "No blocked users": "Aucun utilisateur bloqué",
        "Unblock": "Débloquer",
        "Unblocking…": "Déblocage…",
        "Block user": "Bloquer l’utilisateur",
        "Block": "Bloquer",
        "Profile unavailable": "Profil indisponible",
        "Create story": "Créer une story",
        "Your story": "Votre story",
        "Story viewers": "Vues de la story",
        "Pause": "Mettre en pause",
        "Resume": "Reprendre",
        "Share your feedback": "Partagez vos commentaires",
        "What’s on your mind?": "À quoi pensez-vous ?",
        "Send feedback": "Envoyer",
        "Name (optional)": "Nom (facultatif)",
        "Email (optional)": "E-mail (facultatif)",
        "Thanks for helping improve nook!": "Merci de contribuer à l’amélioration de nook !",
        "Edit Profile": "Modifier le profil",
        "Discover people": "Découvrir des personnes",
        "Back to profile": "Retour au profil",
        "Back to settings": "Retour aux paramètres",
        "No saved posts yet.": "Aucune publication enregistrée pour le moment.",
        "When people follow this profile, they’ll appear here.": "Les personnes qui suivent ce profil apparaîtront ici.",
        "The profiles they follow will appear here.": "Les profils suivis apparaîtront ici.",
        "Load more": "Afficher plus",
        "Couldn’t load. Tap to retry.": "Chargement impossible. Touchez pour réessayer.",
        "Something went wrong. Check your connection and try again.": "Une erreur s’est produite. Vérifiez votre connexion et réessayez.",
        "You’ve blocked this account. Unblock them to see their posts and interact again.": "Vous avez bloqué ce compte. Débloquez-le pour voir ses publications et interagir à nouveau.",
        "No one here yet.": "Personne pour le moment.",
        "Tap to resume": "Touchez pour reprendre",
        "Edit story": "Modifier la story",
        "Delete story": "Supprimer la story",
        "Keep story": "Conserver la story",
        "Story unavailable": "Story indisponible",
        "This story is no longer available.": "Cette story n’est plus disponible.",
        "What would you like to share?": "Que souhaitez-vous partager ?",
        "Add a caption…": "Ajouter une légende…",
        "Publish": "Publier",
        "Publishing…": "Publication…",
        "Discard": "Abandonner",
        "Discard changes?": "Abandonner les modifications ?",
        "Edit post": "Modifier la publication",
        "Save changes": "Enregistrer les modifications",
        "Saving…": "Enregistrement…",
        "Could not load your profile": "Impossible de charger votre profil",
        "Your profile": "Votre profil",
        "Username": "Nom d’utilisateur",
        "Name": "Nom",
        "Bio": "Bio",
        "Website": "Site web",
        "Location": "Lieu",
        "Photo": "Photo",
        "Camera": "Appareil photo",
        "No conversations yet.": "Aucune conversation pour le moment.",
        "Message requests": "Demandes de message",
        "Accept": "Accepter",
        "Decline": "Refuser",
        "Today": "Aujourd’hui",
        "Yesterday": "Hier",
        "Active now": "Actif maintenant",
        "Last seen": "Vu(e) pour la dernière fois",
        "Unknown": "Inconnu",
        "Search nook": "Rechercher sur nook",
        "People": "Personnes",
        "For you": "Pour vous",
        "Recent": "Récent",
        "Clear": "Effacer",
        "No results found.": "Aucun résultat trouvé.",
        "Signed in as": "Connecté(e) en tant que",
        "Could not change language": "Impossible de changer de langue",
        "Please try again.": "Veuillez réessayer.",
        "Preview account": "Compte de démonstration",
        "Sign out is available from your live profile.": "Vous pouvez vous déconnecter depuis votre profil actif.",
        "Unable to sign out": "Impossible de se déconnecter",
        "Unable to open email": "Impossible d’ouvrir l’e-mail",
        "Unable to open link": "Impossible d’ouvrir le lien",
        "Edit your profile photo": "Modifier votre photo de profil",
        "Go back": "Retour",
        "Tagged": "Identifications",
        "Try again": "Réessayer",
        "Could not unblock user": "Impossible de débloquer cet utilisateur",
        "Couldn’t load your blocked users.": "Impossible de charger les utilisateurs bloqués.",
        "People you block will appear here. You can unblock them at any time.": "Les personnes que vous bloquez apparaîtront ici. Vous pourrez les débloquer à tout moment.",
        "Unblock user": "Débloquer l’utilisateur",
        "Unblock @": "Débloquer @",
        "Continue": "Continuer",
        "Group messaging": "Messages de groupe",
        "Conversation unavailable": "Conversation indisponible",
        "Back to messages": "Retour aux messages",
        "Your feed starts here": "Votre fil d’actualité commence ici",
        "Explore the community": "Découvrir la communauté",
        "story": "story",
        "post": "publication",
        "Keep this screen open while your": "Gardez cet écran ouvert pendant que votre",
        "is being shared.": "est en cours de partage.",
        "Write a caption…": "Écrire une légende…",
        "Share story": "Partager la story",
        "Send a link to this story": "Envoyer un lien vers cette story",
        "Remove it before it expires": "La supprimer avant son expiration",
        "Post unavailable": "Publication indisponible",
        "Media unavailable. Tap to retry.": "Média indisponible. Touchez pour réessayer.",
        "Search people, posts, or topics...": "Rechercher des personnes, publications ou sujets…",
        "Search name or username": "Rechercher un nom ou un nom d’utilisateur",
        "Load earlier messages": "Charger les messages précédents",
        "Could not load reactions": "Impossible de charger les réactions",
        "Could not update message request": "Impossible de mettre à jour la demande de message",
        "Could not react to message": "Impossible de réagir au message",
        "Could not edit message": "Impossible de modifier le message",
        "Could not delete message": "Impossible de supprimer le message",
        "Could not open chat": "Impossible d’ouvrir la conversation",
        "Could not update like": "Impossible de mettre à jour le J’aime",
        "Could not update follow": "Impossible de mettre à jour l’abonnement",
        "Create a post": "Créer une publication",
        "Edited": "Modifié",
        "Sending…": "Envoi…",
        "Delivered": "Distribué",
        "You": "Vous",
        "Dismiss reactions": "Fermer les réactions",
        "Message options": "Options du message",
        "This message will be removed only from your chat.": "Ce message sera supprimé uniquement de votre conversation.",
        "This message will be removed for everyone in the conversation.": "Ce message sera supprimé pour tout le monde dans la conversation.",
        "Close message options": "Fermer les options du message",
        "Delete message?": "Supprimer le message ?",
        "React with": "Réagir avec",
        "Remove": "Supprimer",
        "Cancel editing": "Annuler la modification",
        "Cancel reply": "Annuler la réponse",
        "Decline message request": "Refuser la demande de message",
        "Accept message request": "Accepter la demande de message",
        "Open emoji picker": "Ouvrir le sélecteur d’émojis",
        "No conversations yet": "Aucune conversation pour le moment",
        "Retry sharing": "Réessayer le partage",
        "Opening conversation…": "Ouverture de la conversation…",
        "Couldn’t open conversation": "Impossible d’ouvrir la conversation",
        "Check your connection and try again.": "Vérifiez votre connexion et réessayez.",
        "Search members to message": "Rechercher des membres à qui écrire",
        "Cancel block confirmation": "Annuler la confirmation du blocage",
        "They won’t be able to see your posts or message you. You won’t see their posts, and you’ll both be unfollowed.": "Cette personne ne pourra pas voir vos publications ni vous envoyer de message. Vous ne verrez pas ses publications et vous cesserez mutuellement de vous suivre.",
        "Blocking…": "Blocage…",
        "Saving your profile": "Enregistrement de votre profil",
        "Saving": "Enregistrement",
        "Close reaction details": "Fermer les détails des réactions",
        "Could not share": "Impossible de partager",
        "Could not save bookmark": "Impossible d’enregistrer le favori",
        "Could not delete comment": "Impossible de supprimer le commentaire",
        "Could not save profile": "Impossible d’enregistrer le profil",
        "Could not update": "Impossible de mettre à jour",
        "Check your profile": "Vérifiez votre profil",
        "Your unsaved profile changes will be lost.": "Les modifications non enregistrées de votre profil seront perdues.",
        "Keep editing": "Continuer la modification",
        "Choose a JPG or PNG": "Choisissez un fichier JPG ou PNG",
        "Please select a JPG or PNG image for your profile photo.": "Veuillez sélectionner une image JPG ou PNG pour votre photo de profil.",
        "Choose a smaller photo": "Choisissez une photo plus petite",
        "Select an image with a known size of 5 MB or less.": "Sélectionnez une image dont la taille est connue et inférieure ou égale à 5 Mo.",
        "Unable to open photos": "Impossible d’ouvrir les photos",
        "Please try opening the photo library again.": "Veuillez réessayer d’ouvrir la photothèque.",
        "Choose a username": "Choisissez un nom d’utilisateur",
        "Your name": "Votre nom",
        "Tell people about yourself": "Parlez de vous",
        "City, country": "Ville, pays",
        "Save profile": "Enregistrer le profil",
        "Change profile photo": "Modifier la photo de profil",
        "Change Photo": "Modifier la photo",
        "JPG, PNG up to 5MB": "JPG ou PNG, jusqu’à 5 Mo",
        "This is how people find you on nook.": "C’est ainsi que les autres vous trouvent sur nook.",
        "Display Name": "Nom affiché",
        "This is your public name.": "C’est votre nom public.",
        "Share your first moment, or discover people to follow.": "Partagez votre premier moment ou découvrez des personnes à suivre.",
        "Unread": "Non lus",
        "Groups": "Groupes",
        "For now, start a private conversation with one member.": "Pour le moment, démarrez une conversation privée avec un membre.",
        "You’re all caught up": "Vous êtes à jour",
        "You don’t have any unread messages.": "Vous n’avez aucun message non lu.",
        "Start a conversation with someone in the community.": "Commencez une conversation avec un membre de la communauté.",
        "We couldn’t open this conversation. Check your connection and that you’re signed in with the right account.": "Impossible d’ouvrir cette conversation. Vérifiez votre connexion et que vous utilisez le bon compte.",
        "Search Explore": "Rechercher dans Explorer",
        "No posts found. Try another search or topic.": "Aucune publication trouvée. Essayez une autre recherche ou un autre sujet.",
        "Search people, posts, or topics": "Rechercher des personnes, publications ou sujets",
        "Suggested for you": "Suggestions pour vous",
        "See all suggested people": "Voir toutes les personnes suggérées",
        "See all": "Tout voir",
        "No suggested people yet.": "Aucune suggestion de personne pour le moment.",
        "Choose a topic": "Choisir un sujet",
        "Open": "Ouvrir",
        "View": "Voir",
        "Options for": "Options pour",
        "topic": "sujet",
        "All": "Tout",
        "Travel": "Voyage",
        "Nature": "Nature",
        "Pets": "Animaux",
        "Food": "Cuisine",
        "Design": "Design",
        "Lifestyle": "Mode de vie",
        "Open post": "Ouvrir la publication",
        "Post options": "Options de la publication",
        "Unlike post": "Retirer le J’aime",
        "Like post": "Aimer la publication",
        "View comments": "Voir les commentaires",
        "Add your story": "Ajouter votre story",
        "Story": "Story",
        "More story options": "Plus d’options pour la story",
        "Previous story": "Story précédente",
        "Next story": "Story suivante",
        "Finishing publication": "Finalisation de la publication",
        "Keep this screen open while the server confirms your": "Gardez cet écran ouvert pendant que le serveur confirme votre",
        "Cancel upload?": "Annuler l’envoi ?",
        "Your unfinished upload will be discarded.": "Votre envoi inachevé sera abandonné.",
        "Your unfinished upload and caption will be discarded.": "Votre envoi inachevé et sa légende seront abandonnés.",
        "Keep uploading": "Continuer l’envoi",
        "Cancel upload": "Annuler l’envoi",
        "Discard story?": "Abandonner la story ?",
        "Discard post?": "Abandonner la publication ?",
        "Your selected photo will be discarded.": "La photo sélectionnée sera abandonnée.",
        "Your selected media and caption will be discarded.": "Le média sélectionné et sa légende seront abandonnés.",
        "Your text post will be discarded.": "Votre publication textuelle sera abandonnée.",
        "Close composer": "Fermer l’éditeur",
        "New story": "Nouvelle story",
        "New post": "Nouvelle publication",
        "Share post": "Partager la publication",
        "Posting…": "Publication…",
        "Select a photo for your story": "Sélectionner une photo pour votre story",
        "Select a photo for your post": "Sélectionner une photo pour votre publication",
        "Change media": "Modifier le média",
        "Add media": "Ajouter un média",
        "Media": "Média",
        "Opening…": "Ouverture…",
        "Change selected media": "Modifier le média sélectionné",
        "sec": "s",
        "Post caption": "Légende de la publication",
        "Uploading": "Envoi en cours",
        "Preparing media…": "Préparation du média…",
        "Delete post?": "Supprimer la publication ?",
        "Send a link to this post": "Envoyer un lien vers cette publication",
        "Remove this post": "Supprimer cette publication",
        "Search people and posts": "Rechercher des personnes et des publications",
        "Close": "Fermer",
        "Close post options": "Fermer les options de la publication",
        "This removes the post, its media, likes, and comments.": "La publication, ses médias, ses mentions J’aime et ses commentaires seront supprimés.",
        "OK": "OK",
        "Shares a link that opens this post in nook": "Partage un lien qui ouvre cette publication dans nook",
        "Delete comment?": "Supprimer le commentaire ?",
        "This comment and its replies will no longer be visible.": "Ce commentaire et ses réponses ne seront plus visibles.",
        "This post may have been deleted.": "Cette publication a peut-être été supprimée.",
        "Close story viewers": "Fermer la liste des vues de la story",
        "Close story options": "Fermer les options de la story",
        "Cancel deleting story": "Annuler la suppression de la story",
        "Dismiss message": "Fermer le message",
        "Version": "Version",
        "Welcome": "Bienvenue",
        "Sign in to continue to your account and pick up where you left off.": "Connectez-vous à votre compte pour reprendre là où vous en étiez.",
        "Signing in…": "Connexion…",
        "By continuing, you agree to our": "En continuant, vous acceptez nos",
        "and acknowledge our": "et reconnaissez notre",
        "Completing sign in": "Finalisation de la connexion",
        "Nook": "Nook",
        "Finishing sign in": "Finalisation de la connexion",
        "Getting things ready": "Préparation en cours",
        "Your account is being connected securely. This will only take a moment.": "Votre compte est connecté de manière sécurisée. Cela ne prendra qu’un instant.",
        "Signing in": "Connexion",
        "Secure sign-in": "Connexion sécurisée",
        "Newest first": "Plus récents d’abord",
        "Oldest first": "Plus anciens d’abord",
        "Sort comments": "Trier les commentaires",
        "Newest": "Plus récents",
        "Oldest": "Plus anciens",
        "Close sort menu": "Fermer le menu de tri",
        "Comment options": "Options du commentaire",
        "Edit or delete your comment": "Modifier ou supprimer votre commentaire",
        "Close comment options": "Fermer les options du commentaire",
        "Edit comment": "Modifier le commentaire",
        "Delete comment": "Supprimer le commentaire",
        "Unlike comment": "Retirer le J’aime du commentaire",
        "Like comment": "Aimer le commentaire",
        "Couldn’t load saved posts. Tap Saved again to retry.": "Impossible de charger les publications enregistrées. Touchez « Enregistré » pour réessayer.",
        "Tagged posts are not available yet.": "Les publications identifiées ne sont pas encore disponibles.",
        "No videos from": "Aucune vidéo de",
        "yet.": "pour le moment.",
        "No posts yet. Your moments will appear here.": "Aucune publication pour le moment. Vos moments apparaîtront ici.",
        "No posts yet.": "Aucune publication pour le moment.",
        "hasn’t shared any moments.": "n’a partagé aucun moment pour le moment.",
        "This profile isn’t available.": "Ce profil n’est pas disponible.",
        "No followers yet": "Aucun abonné pour le moment",
        "Not following anyone yet": "Ne suit personne pour le moment",
        "User": "Utilisateur",
    },
    ts: {
        "Home": "Kaya",
        "Explore": "Kambisisa",
        "Messages": "Mahungu",
        "Profile": "Profayili",
        "Settings": "Swiyimiso",
        "Account": "Akhawunti",
        "Preferences": "Leswi u swi rhandzaka",
        "Privacy & security": "Xihundla ni vuhlayiseki",
        "Your activity": "Mitirho ya wena",
        "Biometric app lock": "Ku lota app hi swikun’wana swa miri",
        "Remember presence sign-in": "Tsundzuka ku nghena ka vukona",
        "Keeps Nook presence sign-in saved on this device between app launches.": "Swi hlayisa ku nghena ka vukona bya Nook eka xitirhisiwa lexi loko u pfula app nakambe.",
        "Unable to load sign-in preference": "A swi kotekanga ku pakiwa ku hlawula ka ku nghena",
        "Could not update sign-in preference": "A swi kotekanga ku cinca ku hlawula ka ku nghena",
        "Protect your nook": "Sirhelela nook ya wena",
        "Would you like to turn on biometric unlock to help keep your account private?": "Xana u lava ku pfula ku pfula hi swikun’wana swa miri leswaku akhawunti ya wena yi hlayiseka?",
        "Turn on biometric lock": "Pfula ku lota hi swikun’wana swa miri",
        "Not now": "Ku nga ri sweswi",
        "Biometrics unavailable": "Swikun’wana swa miri a swi kumeki",
        "Set up Face ID or fingerprint unlock in your device settings first.": "Rhanga u lulamisa Face ID kumbe ku pfula hi xikun’wana eka swiyimiso swa xitirhisiwa xa wena.",
        "Could not update biometric app lock": "A swi kotekanga ku cinca ku lota app",
        "Biometric authentication failed. Please try again.": "Ku tiyisisa hi swikun’wana swa miri swi tsandzekile. Ringeta nakambe.",
        "Set up Face ID or fingerprint unlock on your device first.": "Rhanga u lulamisa Face ID kumbe ku pfula hi xikun’wana eka xitirhisiwa xa wena.",
        "Biometric app lock is available only on a supported mobile device.": "Ku lota app hi swikun’wana swa miri ku tirha ntsena eka xitirhisiwa xa riqingho lexi seketeriwaka.",
        "Enable biometric app lock": "Pfula ku lota app hi swikun’wana swa miri",
        "Disable biometric app lock": "Tima ku lota app hi swikun’wana swa miri",
        "Unlock nook": "Pfula nook",
        "Nook is locked": "Nook yi lotiwile",
        "Verify your identity to continue.": "Tiyisisa leswaku hi wena leswaku u ya mahlweni.",
        "Unlock with biometrics": "Pfula hi swikun’wana swa miri",
        "Verifying…": "Swa tiyisisiwa…",
        "Checking…": "Swa kamberiwa…",
        "On": "Swi pfurile",
        "Off": "Swi timiwile",
        "Unavailable": "A swi kumeki",
        "Support & Legal": "Nseketelo na swa le nawini",
        "Help & support": "Mpfuneto ni nseketelo",
        "Edit profile": "Hlela profayili",
        "Saved posts": "Tiphostu leti hlayisiweke",
        "Blocked users": "Vatirhisi lava siveriweke",
        "Report a problem": "Tivisa hi xiphiqo",
        "Privacy Policy": "Pholisi ya Xihundla",
        "Terms of Service": "Swipimelo swa Vukorhokeri",
        "About": "Mayelana",
        "Share feedback": "Avela mavonelo",
        "Sign Out": "Huma",
        "Signing out…": "Ku huma…",
        "Language": "Ririmi",
        "Choose the language used in nook.": "Hlawula ririmi leri tirhisiwaka eka nook.",
        "English": "Xinghezi",
        "isiZulu": "isiZulu",
        "Cancel": "Khansela",
        "Save": "Hlayisa",
        "Done": "Swi herile",
        "Retry": "Ringeta nakambe",
        "Loading…": "Swa layicha…",
        "Search": "Lava",
        "Search people": "Lava vanhu",
        "Search posts": "Lava tiphostu",
        "Follow": "Landzelela",
        "Following": "Wa landzelela",
        "Followers": "Valandzeri",
        "Unfollow": "Tshika ku landzelela",
        "Message": "Rungula",
        "Post": "Phostu",
        "Posts": "Tiphostu",
        "Videos": "Tivhidiyo",
        "Saved": "Swi hlayisiwile",
        "Like": "Tsakela",
        "Unlike": "Tshika ku tsakela",
        "Comment": "Nhlamuselo",
        "Comments": "Tinhlamuselo",
        "Reply": "Hlamula",
        "Replies": "Tinhlamulo",
        "Share": "Avela",
        "Edit": "Hlela",
        "Delete": "Sula",
        "Write a comment…": "Tsala nhlamuselo…",
        "Write a reply…": "Tsala nhlamulo…",
        "Send": "Rhumela",
        "Send message": "Rhumela rungula",
        "Type a message…": "Tsala rungula…",
        "Online": "U le ka inthanete",
        "Offline": "A nga ri ka inthanete",
        "New message": "Rungula lerintshwa",
        "No messages yet.": "A ku na mahungu sweswi.",
        "No videos to show.": "A ku na tivhidiyo leti kombisiwaka.",
        "No blocked users": "A ku na vatirhisi lava siveriweke",
        "Unblock": "Pfulela",
        "Unblocking…": "Ku pfuriwa…",
        "Block user": "Sivela mutirhisi",
        "Block": "Sivela",
        "Profile unavailable": "Profayili a yi kumeki",
        "Create story": "Endla ntsheketo",
        "Your story": "Ntsheketo wa wena",
        "Story viewers": "Vahlaleri va ntsheketo",
        "Pause": "Yimisa",
        "Resume": "Yana mahlweni",
        "Share your feedback": "Avela mavonelo ya wena",
        "What’s on your mind?": "U ehleketa yini?",
        "Send feedback": "Rhumela mavonelo",
        "Name (optional)": "Vito (swa ku hlawula)",
        "Email (optional)": "Imeyili (swa ku hlawula)",
        "Thanks for helping improve nook!": "Ha khensa ku pfuna ku antswisa nook!",
        "Edit Profile": "Hlela profayili",
        "Discover people": "Kuma vanhu",
        "Back to profile": "Tlhela eka profayili",
        "Back to settings": "Tlhela eka swiyimiso",
        "No saved posts yet.": "A ku na tiphostu leti hlayisiweke.",
        "When people follow this profile, they’ll appear here.": "Vanhu lava landzelaka profayili leyi va ta vonaka laha.",
        "The profiles they follow will appear here.": "Tiprofayili leti va ti landzelaka ti ta vonaka laha.",
        "Load more": "Layicha swin'wana",
        "Couldn’t load. Tap to retry.": "A swi kotekanga ku layicha. Koma leswaku u ringeta nakambe.",
        "Something went wrong. Check your connection and try again.": "Ku humelele xiphiqo. Kambela vuhlanganisi bya wena kutani u ringeta nakambe.",
        "You’ve blocked this account. Unblock them to see their posts and interact again.": "U siverile akhawunti leyi. Yi pfulele leswaku u vona tiphostu ta yona ni ku tlhela mi tirhisana.",
        "No one here yet.": "A ku na munhu laha sweswi.",
        "Tap to resume": "Koma leswaku u ya mahlweni",
        "Edit story": "Hlela ntsheketo",
        "Delete story": "Sula ntsheketo",
        "Keep story": "Hlayisa ntsheketo",
        "Story unavailable": "Ntsheketo a wu kumeki",
        "This story is no longer available.": "Ntsheketo lowu a wa ha kumeki.",
        "What would you like to share?": "U lava ku avela yini?",
        "Add a caption…": "Engetela nhlamuselo…",
        "Publish": "Komba",
        "Publishing…": "Swa kandziyisiwa…",
        "Discard": "Lahla",
        "Discard changes?": "Lahla ku cinca?",
        "Edit post": "Hlela phostu",
        "Save changes": "Hlayisa ku cinca",
        "Saving…": "Swa hlayisiwa…",
        "Could not load your profile": "A swi kotekanga ku layicha profayili ya wena",
        "Your profile": "Profayili ya wena",
        "Username": "Vito ra mutirhisi",
        "Name": "Vito",
        "Bio": "Mayelana na wena",
        "Website": "Webusayiti",
        "Location": "Ndhawu",
        "Photo": "Xifaniso",
        "Camera": "Khamera",
        "No conversations yet.": "A ku na mabulo sweswi.",
        "Message requests": "Swikombelo swa rungula",
        "Accept": "Amukela",
        "Decline": "Landzula",
        "Today": "Namuntlha",
        "Yesterday": "Toxe",
        "Active now": "Wa tirha sweswi",
        "Last seen": "U hetelele ku voniwa",
        "Unknown": "A swi tiviwi",
        "Search nook": "Lava eka nook",
        "People": "Vanhu",
        "For you": "Swa wena",
        "Recent": "Swa sweswinyana",
        "Clear": "Sula",
        "No results found.": "A ku kumekanga leswi lavekaka.",
        "Signed in as": "U nghene tani hi",
        "Could not change language": "A swi kotekanga ku cinca ririmi",
        "Please try again.": "Hi kombela u ringeta nakambe.",
        "Preview account": "Akhawunti yo kambisisa",
        "Sign out is available from your live profile.": "U nga huma eka profayili ya wena leyi tirhaka.",
        "Unable to sign out": "A swi kotekanga ku huma",
        "Unable to open email": "A swi kotekanga ku pfula imeyili",
        "Unable to open link": "A swi kotekanga ku pfula xihlanganisi",
        "Edit your profile photo": "Hlela xifaniso xa profayili ya wena",
        "Go back": "Tlhela endzhaku",
        "Tagged": "Laha u leburiweke kona",
        "Try again": "Ringeta nakambe",
        "Could not unblock user": "A swi kotekanga ku pfulela mutirhisi",
        "Couldn’t load your blocked users.": "A swi kotekanga ku layicha vatirhisi lava u va siverile.",
        "People you block will appear here. You can unblock them at any time.": "Vanhu lava u va siveraka va ta vonaka laha. U nga va pfulela nkarhi wun'wana ni wun'wana.",
        "Unblock user": "Pfulela mutirhisi",
        "Unblock @": "Pfulela @",
        "Continue": "Yana mahlweni",
        "Group messaging": "Mahungu ya ntlawa",
        "Conversation unavailable": "Bulo a ri kumeki",
        "Back to messages": "Tlhela eka mahungu",
        "Your feed starts here": "Mahungu ya wena ma sungula laha",
        "Explore the community": "Kambisisa vaaki",
        "story": "ntsheketo",
        "post": "phostu",
        "Keep this screen open while your": "Tshama u pfule xikirini lexi loko",
        "is being shared.": "swa averiwa.",
        "Write a caption…": "Tsala nhlamuselo…",
        "Share story": "Avela ntsheketo",
        "Send a link to this story": "Rhumela xihlanganisi xa ntsheketo lowu",
        "Remove it before it expires": "Wu suse wu nga si hela nkarhi wa wona",
        "Post unavailable": "Phostu a yi kumeki",
        "Media unavailable. Tap to retry.": "Media a yi kumeki. Koma u ringeta nakambe.",
        "Search people, posts, or topics...": "Lava vanhu, tiphostu kumbe tinhlokomhaka…",
        "Search name or username": "Lava vito kumbe vito ra mutirhisi",
        "Load earlier messages": "Layicha mahungu ya khale",
        "Could not load reactions": "A swi kotekanga ku layicha swiendlo",
        "Could not update message request": "A swi kotekanga ku cinca xikombelo xa rungula",
        "Could not react to message": "A swi kotekanga ku hlamula rungula",
        "Could not edit message": "A swi kotekanga ku hlela rungula",
        "Could not delete message": "A swi kotekanga ku sula rungula",
        "Could not open chat": "A swi kotekanga ku pfula bulo",
        "Could not update like": "A swi kotekanga ku cinca ku tsakela",
        "Could not update follow": "A swi kotekanga ku cinca ku landzelela",
        "Create a post": "Endla phostu",
        "Edited": "Swi hleriwile",
        "Sending…": "Swa rhumeriwa…",
        "Delivered": "Swi fikile",
        "You": "Wena",
        "Dismiss reactions": "Pfala swiendlo",
        "Message options": "Swihlawulekisi swa rungula",
        "This message will be removed only from your chat.": "Rungula leri ri ta susiwa eka bulo ra wena ntsena.",
        "This message will be removed for everyone in the conversation.": "Rungula leri ri ta susiwa eka vanhu hinkwavo ebulweni.",
        "Close message options": "Pfala swihlawulekisi swa rungula",
        "Delete message?": "Sula rungula?",
        "React with": "Hlamula hi",
        "Remove": "Susa",
        "Cancel editing": "Khansela ku hlela",
        "Cancel reply": "Khansela nhlamulo",
        "Decline message request": "Landzula xikombelo xa rungula",
        "Accept message request": "Amukela xikombelo xa rungula",
        "Open emoji picker": "Pfula ku hlawula emoji",
        "No conversations yet": "A ku na mabulo sweswi",
        "Retry sharing": "Ringeta ku avela nakambe",
        "Opening conversation…": "Ku pfula bulo…",
        "Couldn’t open conversation": "A swi kotekanga ku pfula bulo",
        "Check your connection and try again.": "Kambela vuhlanganisi bya wena kutani u ringeta nakambe.",
        "Search members to message": "Lava swirho swo swi rhumela rungula",
        "Cancel block confirmation": "Khansela ku tiyisisa ku sivela",
        "They won’t be able to see your posts or message you. You won’t see their posts, and you’ll both be unfollowed.": "A va nge swi koti ku vona tiphostu ta wena kumbe ku ku rhumela rungula. Na wena a wu nge ti voni tiphostu ta vona naswona mi ta tshika ku landzelelana.",
        "Blocking…": "Ku sivela…",
        "Saving your profile": "Ku hlayisa profayili ya wena",
        "Saving": "Ku hlayisa",
        "Close reaction details": "Pfala vuxokoxoko bya swiendlo",
        "Could not share": "A swi kotekanga ku avela",
        "Could not save bookmark": "A swi kotekanga ku hlayisa xihlayisi",
        "Could not delete comment": "A swi kotekanga ku sula nhlamuselo",
        "Could not save profile": "A swi kotekanga ku hlayisa profayili",
        "Could not update": "A swi kotekanga ku cinca",
        "Check your profile": "Kambela profayili ya wena",
        "Your unsaved profile changes will be lost.": "Ku cinca ka profayili ya wena loku nga hlayisiwangiki ku ta lahleka.",
        "Keep editing": "Yana mahlweni u hlela",
        "Choose a JPG or PNG": "Hlawula JPG kumbe PNG",
        "Please select a JPG or PNG image for your profile photo.": "Hi kombela u hlawula xifaniso xa JPG kumbe PNG xa profayili ya wena.",
        "Choose a smaller photo": "Hlawula xifaniso lexitsongo",
        "Select an image with a known size of 5 MB or less.": "Hlawula xifaniso lexi nga na vukulu bya 5 MB kumbe ehansi.",
        "Unable to open photos": "A swi kotekanga ku pfula swifaniso",
        "Please try opening the photo library again.": "Hi kombela u ringeta ku pfula layiburari ya swifaniso nakambe.",
        "Choose a username": "Hlawula vito ra mutirhisi",
        "Your name": "Vito ra wena",
        "Tell people about yourself": "Byela vanhu hi wena",
        "City, country": "Doroba, tiko",
        "Save profile": "Hlayisa profayili",
        "Change profile photo": "Cinca xifaniso xa profayili",
        "Change Photo": "Cinca xifaniso",
        "JPG, PNG up to 5MB": "JPG, PNG kufika eka 5MB",
        "This is how people find you on nook.": "Leswi swi pfuna vanhu ku ku kuma eka nook.",
        "Display Name": "Vito leri kombisiwaka",
        "This is your public name.": "Leri i vito ra wena ra mani na mani.",
        "Share your first moment, or discover people to follow.": "Avela nkarhi wa wena wo sungula kumbe kuma vanhu vo va landzelela.",
        "Unread": "Leyi nga hlayiwangiki",
        "Groups": "Mintlawa",
        "For now, start a private conversation with one member.": "Sweswi, sungula bulo ra xihundla ni xirho xin'we.",
        "You’re all caught up": "U kumile mahungu hinkwawu ya sweswi",
        "You don’t have any unread messages.": "A wu na mahungu lawa u nga ma hlayangiki.",
        "Start a conversation with someone in the community.": "Sungula bulo ni munhu wa le ka vaaki.",
        "We couldn’t open this conversation. Check your connection and that you’re signed in with the right account.": "A swi kotekanga ku pfula bulo leri. Kambela vuhlanganisi bya wena ni ku tiyisisa leswaku u nghene hi akhawunti leyinene.",
        "Search Explore": "Lava eka Kambisisa",
        "No posts found. Try another search or topic.": "A ku kumekanga tiphostu. Ringeta ku lava swin'wana kumbe nhlokomhaka yin'wana.",
        "Search people, posts, or topics": "Lava vanhu, tiphostu kumbe tinhlokomhaka",
        "Suggested for you": "Swi ringanyetiwe wena",
        "See all suggested people": "Vona vanhu hinkwavo lava ringanyetiweke",
        "See all": "Vona hinkwaswu",
        "No suggested people yet.": "A ku na vanhu lava ringanyetiweke sweswi.",
        "Choose a topic": "Hlawula nhlokomhaka",
        "Open": "Pfula",
        "View": "Vona",
        "Options for": "Swihlawulekisi swa",
        "topic": "nhlokomhaka",
        "All": "Hinkwaswu",
        "Travel": "Riendzo",
        "Nature": "Ntumbuluko",
        "Pets": "Swifuwo",
        "Food": "Swakudya",
        "Design": "Dizayini",
        "Lifestyle": "Mahanyelo",
        "Open post": "Pfula phostu",
        "Post options": "Swihlawulekisi swa phostu",
        "Unlike post": "Tshika ku tsakela phostu",
        "Like post": "Tsakela phostu",
        "View comments": "Vona tinhlamuselo",
        "Add your story": "Engetela ntsheketo wa wena",
        "Story": "Ntsheketo",
        "More story options": "Swihlawulekisi swin'wana swa ntsheketo",
        "Previous story": "Ntsheketo lowu hundzeke",
        "Next story": "Ntsheketo lowu landzelaka",
        "Finishing publication": "Ku hetisa ku kandziyisa",
        "Keep this screen open while the server confirms your": "Tshama u pfule xikirini lexi loko sevha yi tiyisisa",
        "Cancel upload?": "Khansela ku layicha?",
        "Your unfinished upload will be discarded.": "Ku layicha ka wena loku nga hetiwekangiki ku ta lahliwa.",
        "Your unfinished upload and caption will be discarded.": "Ku layicha ni nhlamuselo ya wena leswi nga hetiwekangiki swi ta lahliwa.",
        "Keep uploading": "Yana mahlweni u layicha",
        "Cancel upload": "Khansela ku layicha",
        "Discard story?": "Lahla ntsheketo?",
        "Discard post?": "Lahla phostu?",
        "Your selected photo will be discarded.": "Xifaniso lexi u xi hlawuleke xi ta lahliwa.",
        "Your selected media and caption will be discarded.": "Media ni nhlamuselo leswi u swi hlawuleke swi ta lahliwa.",
        "Your text post will be discarded.": "Phostu ya wena ya marito yi ta lahliwa.",
        "Close composer": "Pfala muandlari",
        "New story": "Ntsheketo lowuntshwa",
        "New post": "Phostu leyintshwa",
        "Share post": "Avela phostu",
        "Posting…": "Ku kandziyisa…",
        "Select a photo for your story": "Hlawula xifaniso xa ntsheketo wa wena",
        "Select a photo for your post": "Hlawula xifaniso xa phostu ya wena",
        "Change media": "Cinca media",
        "Add media": "Engetela media",
        "Media": "Media",
        "Opening…": "Ku pfula…",
        "Change selected media": "Cinca media leyi hlawuriweke",
        "sec": "s",
        "Post caption": "Nhlamuselo ya phostu",
        "Uploading": "Ku layicha",
        "Preparing media…": "Ku lulamisa media…",
        "Delete post?": "Sula phostu?",
        "Send a link to this post": "Rhumela xihlanganisi xa phostu leyi",
        "Remove this post": "Sula phostu leyi",
        "Search people and posts": "Lava vanhu ni tiphostu",
        "Close": "Pfala",
        "Close post options": "Pfala swihlawulekisi swa phostu",
        "This removes the post, its media, likes, and comments.": "Leswi swi ta sula phostu, media ya yona, ku tsakela ni tinhlamuselo.",
        "OK": "SWI LUNGE",
        "Shares a link that opens this post in nook": "Avela xihlanganisi lexi pfulaka phostu leyi eka nook",
        "Delete comment?": "Sula nhlamuselo?",
        "This comment and its replies will no longer be visible.": "Nhlamuselo leyi ni tinhlamulo ta yona a swi nge he vonaki.",
        "This post may have been deleted.": "Kumbexana phostu leyi yi suriwile.",
        "Close story viewers": "Pfala vahlaleri va ntsheketo",
        "Close story options": "Pfala swihlawulekisi swa ntsheketo",
        "Cancel deleting story": "Khansela ku sula ntsheketo",
        "Dismiss message": "Pfala rungula",
        "Version": "Vuhundzuluxi",
        "Welcome": "Amukeriwile",
        "Sign in to continue to your account and pick up where you left off.": "Nghena eka akhawunti ya wena leswaku u ya mahlweni laha u heleleke kona.",
        "Signing in…": "Ku nghena…",
        "By continuing, you agree to our": "Loko u ya mahlweni, u pfumela",
        "and acknowledge our": "naswona u amukela",
        "Completing sign in": "Ku hetisa ku nghena",
        "Nook": "Nook",
        "Finishing sign in": "Ku hetisa ku nghena",
        "Getting things ready": "Ku lulamisa swilo",
        "Your account is being connected securely. This will only take a moment.": "Akhawunti ya wena yi hlanganisiwa hi ndlela leyi sirhelelekeke. Swi ta teka nkarhi wutsongo.",
        "Signing in": "Ku nghena",
        "Secure sign-in": "Ku nghena loku sirhelelekeke",
        "Newest first": "Leswintshwa ku sungula",
        "Oldest first": "Swa khale ku sungula",
        "Sort comments": "Lulamisa tinhlamuselo",
        "Newest": "Leswintshwa",
        "Oldest": "Swa khale",
        "Close sort menu": "Pfala menyu yo lulamisa",
        "Comment options": "Swihlawulekisi swa nhlamuselo",
        "Edit or delete your comment": "Hlela kumbe sula nhlamuselo ya wena",
        "Close comment options": "Pfala swihlawulekisi swa nhlamuselo",
        "Edit comment": "Hlela nhlamuselo",
        "Delete comment": "Sula nhlamuselo",
        "Unlike comment": "Tshika ku tsakela nhlamuselo",
        "Like comment": "Tsakela nhlamuselo",
        "Couldn’t load saved posts. Tap Saved again to retry.": "A swi kotekanga ku layicha tiphostu leti hlayisiweke. Koma eka leti hlayisiweke u ringeta nakambe.",
        "Tagged posts are not available yet.": "Tiphostu leti leburiweke a ti si kumeka.",
        "No videos from": "A ku na tivhidiyo ta",
        "yet.": "sweswi.",
        "No posts yet. Your moments will appear here.": "A ku na tiphostu sweswi. Swilo swa wena swi ta vonaka laha.",
        "No posts yet.": "A ku na tiphostu sweswi.",
        "hasn’t shared any moments.": "a nga si avela swilo swa nkarhi wa yena.",
        "This profile isn’t available.": "Profayili leyi a yi kumeki.",
        "No followers yet": "A ku na valandzeri sweswi",
        "Not following anyone yet": "A landzeli munhu sweswi",
        "User": "Mutirhisi",
        "Sunday": "Sonto",
        "Monday": "Musumbhunuku",
        "Tuesday": "Ravumbirhi",
        "Wednesday": "Ravunharhu",
        "Thursday": "Ravumune",
        "Friday": "Ravuntlhanu",
        "Saturday": "Mugimeto",
    },
};

async function readStoredLanguage(): Promise<NookLanguage | null> {
    try {
        const value = Platform.OS === "web"
            ? typeof localStorage === "undefined"
                ? null
                : localStorage.getItem(STORAGE_KEY)
            : await SecureStore.getItemAsync(STORAGE_KEY);
        return value === "en" || value === "zu" || value === "fr" || value === "ts" ? value : null;
    } catch (error) {
        console.warn("Unable to read saved language preference.", error);
        return null;
    }
}

async function saveStoredLanguage(language: NookLanguage) {
    if (Platform.OS === "web") {
        if (typeof localStorage === "undefined") {
            throw new Error("Language preference storage is unavailable.");
        }
        localStorage.setItem(STORAGE_KEY, language);
        return;
    }
    await SecureStore.setItemAsync(STORAGE_KEY, language);
}

type LanguageContextValue = {
    language: NookLanguage;
    isLanguageLoaded: boolean;
    setLanguage: (language: NookLanguage) => Promise<void>;
    t: (text: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<NookLanguage>("en");
    const [isLanguageLoaded, setIsLanguageLoaded] = useState(false);

    useEffect(() => {
        let active = true;
        void readStoredLanguage().then(saved => {
            if (active && saved) setLanguageState(saved);
            if (active) setIsLanguageLoaded(true);
        });
        return () => {
            active = false;
        };
    }, []);

    const setLanguage = useCallback(async (next: NookLanguage) => {
        await saveStoredLanguage(next);
        setLanguageState(next);
    }, []);

    const value = useMemo<LanguageContextValue>(() => ({
        language,
        isLanguageLoaded,
        setLanguage,
        t: (text: string) => translations[language][text] ?? text,
    }), [isLanguageLoaded, language, setLanguage]);

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useNookLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useNookLanguage must be used inside LanguageProvider.");
    }
    return context;
}
