import * as SecureStore from "expo-secure-store";
import {
    createContext,
    useCallback,
    useContext,
    useEffect,
    useMemo,
    useState,
    type ReactNode,
} from "react";
import { Platform } from "react-native";

export type NookLanguage = "en" | "zu" | "fr";

const STORAGE_KEY = "nook_language";

const translations: Record<NookLanguage, Record<string, string>> = {
    en: {},
    zu: {
        "Home": "Ikhaya",
        "Explore": "Hlola",
        "Messages": "Imilayezo",
        "Profile": "Iphrofayela",
        "Settings": "Izilungiselelo",
        "Account": "I-akhawunti",
        "Support & Legal": "Usizo Nezomthetho",
        "Edit profile": "Hlela iphrofayela",
        "Saved posts": "Okuthunyelwe okulondoloziwe",
        "Blocked users": "Abantu abavinjiwe",
        "Report a problem": "Bika inkinga",
        "Privacy Policy": "Inqubomgomo Yobumfihlo",
        "Terms of Service": "Imigomo Yesevisi",
        "About": "Mayelana",
        "Share feedback": "Yabelana ngempendulo",
        "Sign Out": "Phuma",
        "Signing out…": "Kuyaphunywa…",
        "Language": "Ulimi",
        "Choose the language used in nook.": "Khetha ulimi olusetshenziswa ku-nook.",
        "English": "IsiNgisi",
        "isiZulu": "isiZulu",
        "Cancel": "Khansela",
        "Save": "Londoloza",
        "Done": "Kwenziwe",
        "Retry": "Zama futhi",
        "Loading…": "Kuyalayishwa…",
        "Search": "Sesha",
        "Search people": "Sesha abantu",
        "Search posts": "Sesha okuthunyelwe",
        "Follow": "Landela",
        "Following": "Uyalandela",
        "Followers": "Abalandeli",
        "Unfollow": "Yeka ukulandela",
        "Message": "Thumela umlayezo",
        "Post": "Okuthunyelwe",
        "Posts": "Okuthunyelwe",
        "Videos": "Amavidiyo",
        "Saved": "Kulondoloziwe",
        "Like": "Thanda",
        "Unlike": "Yeka ukuthanda",
        "Comment": "Beka amazwana",
        "Comments": "Amazwana",
        "Reply": "Phendula",
        "Replies": "Izimpendulo",
        "Share": "Yabelana",
        "Edit": "Hlela",
        "Delete": "Susa",
        "Write a comment…": "Bhala amazwana…",
        "Write a reply…": "Bhala impendulo…",
        "Send": "Thumela",
        "Send message": "Thumela umlayezo",
        "Type a message…": "Bhala umlayezo…",
        "Online": "Kuxhunyiwe",
        "Offline": "Akuxhunyiwe",
        "New message": "Umlayezo omusha",
        "No messages yet.": "Akukabi namilayezo.",
        "No posts yet.": "Akukabi nalokhu okuthunyelwe.",
        "No videos to show.": "Awekho amavidiyo azoboniswa.",
        "No blocked users": "Abekho abantu abavinjiwe",
        "Unblock": "Vulela",
        "Unblocking…": "Kuyavulwa…",
        "Block user": "Vimba umuntu",
        "Block": "Vimba",
        "Profile unavailable": "Iphrofayela ayitholakali",
        "Create story": "Dala indaba",
        "Your story": "Indaba yakho",
        "Story viewers": "Ababukele indaba",
        "Pause": "Misa isikhashana",
        "Resume": "Qhubeka",
        "Share your feedback": "Yabelana ngempendulo yakho",
        "What’s on your mind?": "Ucabangani?",
        "Send feedback": "Thumela impendulo",
        "Name (optional)": "Igama (akuphoqelekile)",
        "Email (optional)": "I-imeyili (akuphoqelekile)",
        "Thanks for helping improve nook!": "Siyabonga ngokusiza ukuthuthukisa i-nook!",
        "Edit Profile": "Hlela Iphrofayela",
        "Discover people": "Thola abantu",
        "Back to profile": "Buyela kuphrofayela",
        "Back to settings": "Buyela kuzilungiselelo",
        "No saved posts yet.": "Akukabi nalokhu okuthunyelwe okulondoloziwe.",
        "When people follow this profile, they’ll appear here.": "Uma abantu belandela le phrofayela, bazovela lapha.",
        "The profiles they follow will appear here.": "Amaphrofayela abawalandelayo azovela lapha.",
        "Load more": "Layisha okwengeziwe",
        "Couldn’t load. Tap to retry.": "Ayikwazanga ukulayisha. Thepha ukuze uzame futhi.",
        "Something went wrong. Check your connection and try again.": "Kukhona okungahambanga kahle. Hlola uxhumano lwakho bese uzama futhi.",
        "You’ve blocked this account. Unblock them to see their posts and interact again.": "Uvimbile le akhawunti. Yivulele ukuze ubone okuthunyelwe kwayo futhi uxhumane nayo.",
        "No one here yet.": "Akekho okwamanje.",
        "Tap to resume": "Thepha ukuze uqhubeke",
        "Edit story": "Hlela indaba",
        "Delete story": "Susa indaba",
        "Keep story": "Gcina indaba",
        "Story unavailable": "Indaba ayitholakali",
        "This story is no longer available.": "Le ndaba ayisatholakali.",
        "What would you like to share?": "Yini ongathanda ukuyabelana ngayo?",
        "Add a caption…": "Faka amazwibela…",
        "Publish": "Shicilela",
        "Publishing…": "Kuyashicilelwa…",
        "Discard": "Lahla",
        "Discard changes?": "Lahla izinguquko?",
        "Edit post": "Hlela okuthunyelwe",
        "Save changes": "Londoloza izinguquko",
        "Saving…": "Kuyalondolozwa…",
        "Could not load your profile": "Ayikwazanga ukulayisha iphrofayela yakho",
        "Your profile": "Iphrofayela yakho",
        "Username": "Igama lomsebenzisi",
        "Name": "Igama",
        "Bio": "Mayelana nawe",
        "Website": "Iwebhusayithi",
        "Location": "Indawo",
        "Photo": "Isithombe",
        "Camera": "Ikhamera",
        "No conversations yet.": "Akukabi nezingxoxo.",
        "Message requests": "Izicelo zemilayezo",
        "Accept": "Yamukela",
        "Decline": "Yenqaba",
        "Today": "Namuhla",
        "Yesterday": "Izolo",
        "Active now": "Uyasebenza manje",
        "Last seen": "Ugcinwe ukubonakala",
        "Unknown": "Akwaziwa",
        "Search nook": "Sesha ku-nook",
        "People": "Abantu",
        "For you": "Okwakho",
        "Recent": "Okwakamuva",
        "Clear": "Sula",
        "No results found.": "Ayikho imiphumela etholakele.",
        "Signed in as": "Ungene ngemvume njengo",
        "Could not change language": "Ulimi alukwazanga ukushintshwa",
        "Please try again.": "Sicela uzame futhi.",
        "Preview account": "I-akhawunti yokubuka kuqala",
        "Sign out is available from your live profile.": "Ungaphuma kuphrofayela yakho yangempela.",
        "Unable to sign out": "Ayikwazanga ukuphuma",
        "Edit your profile photo": "Hlela isithombe sakho sephrofayela",
        "Go back": "Buyela emuva",
        "Tagged": "Okumakiwe",
        "Try again": "Zama futhi",
        "Could not unblock user": "Ayikwazanga ukuvulela lo muntu",
        "Couldn’t load your blocked users.": "Ayikwazanga ukulayisha abantu obavimbile.",
        "People you block will appear here. You can unblock them at any time.": "Abantu obavimbayo bazovela lapha. Ungabavulela noma nini.",
        "Unblock user": "Vulela umuntu",
        "Unblock @": "Vulela @",
        "Continue": "Qhubeka",
        "Group messaging": "Imilayezo yeqembu",
        "Conversation unavailable": "Ingxoxo ayitholakali",
        "Back to messages": "Buyela emilayezweni",
        "Your feed starts here": "Okuphakelayo kwakho kuqala lapha",
        "Explore the community": "Hlola umphakathi",
        "story": "indaba",
        "post": "okuthunyelwe",
        "Keep this screen open while your": "Gcina lesi sikrini sivuliwe ngenkathi",
        "is being shared.": "kwabiwa.",
        "Write a caption…": "Bhala amazwibela…",
        "Share story": "Yabelana ngendaba",
        "Send a link to this story": "Thumela isixhumanisi sale ndaba",
        "Remove it before it expires": "Isuse ngaphambi kokuba iphelelwe isikhathi",
        "Post unavailable": "Okuthunyelwe akutholakali",
        "Media unavailable. Tap to retry.": "Imidiya ayitholakali. Thepha ukuze uzame futhi.",
        "Search people, posts, or topics...": "Sesha abantu, okuthunyelwe noma izihloko...",
        "Search name or username": "Sesha igama noma igama lomsebenzisi",
        "Load earlier messages": "Layisha imilayezo emidala",
        "Could not load reactions": "Ayikwazanga ukulayisha ukusabela",
        "Could not update message request": "Ayikwazanga ukubuyekeza isicelo somlayezo",
        "Could not react to message": "Ayikwazanga ukusabela kumlayezo",
        "Could not edit message": "Ayikwazanga ukuhlela umlayezo",
        "Could not delete message": "Ayikwazanga ukususa umlayezo",
        "Could not open chat": "Ayikwazanga ukuvula ingxoxo",
        "Could not update like": "Ayikwazanga ukubuyekeza ukuthanda",
        "Could not update follow": "Ayikwazanga ukubuyekeza ukulandela",
        "Create a post": "Dala okuthunyelwe",
        "Edited": "Kuhleliwe",
        "Sending…": "Kuyathunyelwa…",
        "Delivered": "Kulethiwe",
        "You": "Wena",
        "Dismiss reactions": "Vala ukusabela",
        "Message options": "Izinketho zomlayezo",
        "This message will be removed only from your chat.": "Lo myalezo uzosuswa engxoxweni yakho kuphela.",
        "This message will be removed for everyone in the conversation.": "Lo myalezo uzosuswa kuwo wonke umuntu engxoxweni.",
        "Close message options": "Vala izinketho zomlayezo",
        "Delete message?": "Susa umlayezo?",
        "React with": "Phendula ngo",
        "Remove": "Susa",
        "Cancel editing": "Khansela ukuhlela",
        "Cancel reply": "Khansela impendulo",
        "Decline message request": "Yenqaba isicelo somlayezo",
        "Accept message request": "Yamukela isicelo somlayezo",
        "Open emoji picker": "Vula ukukhetha ama-emoji",
        "No conversations yet": "Akukabi nezingxoxo",
        "Retry sharing": "Zama ukwabelana futhi",
        "Opening conversation…": "Kuvulwa ingxoxo…",
        "Couldn’t open conversation": "Ayikwazanga ukuvula ingxoxo",
        "Check your connection and try again.": "Hlola uxhumano lwakho bese uzama futhi.",
        "Search members to message": "Sesha amalungu ongawathumelela umlayezo",
        "Cancel block confirmation": "Khansela ukuqinisekiswa kokuvimba",
        "They won’t be able to see your posts or message you. You won’t see their posts, and you’ll both be unfollowed.": "Ngeke bakwazi ukubona okuthunyelwe kwakho noma bakuthumele umlayezo. Ngeke ubone okuthunyelwe kwabo, futhi nizoyeka ukulandelana nobabili.",
        "Blocking…": "Kuyavinjwa…",
        "Saving your profile": "Iphrofayela yakho iyalondolozwa",
        "Saving": "Kuyalondolozwa",
        "Close reaction details": "Vala imininingwane yokusabela",
        "Could not share": "Ayikwazanga ukwabelana",
        "Could not save bookmark": "Ayikwazanga ukulondoloza ibhukhimakhi",
        "Could not delete comment": "Ayikwazanga ukususa amazwana",
        "Could not save profile": "Ayikwazanga ukulondoloza iphrofayela",
        "Could not update": "Ayikwazanga ukubuyekeza",
        "Check your profile": "Hlola iphrofayela yakho",
        "Your unsaved profile changes will be lost.": "Izinguquko zephrofayela yakho ezingalondoloziwe zizolahleka.",
        "Keep editing": "Qhubeka nokuhlela",
        "Choose a JPG or PNG": "Khetha i-JPG noma i-PNG",
        "Please select a JPG or PNG image for your profile photo.": "Sicela ukhethe isithombe se-JPG noma se-PNG sesithombe sakho sephrofayela.",
        "Choose a smaller photo": "Khetha isithombe esincane",
        "Select an image with a known size of 5 MB or less.": "Khetha isithombe esinosayizi owaziwayo ongu-5 MB noma ngaphansi.",
        "Unable to open photos": "Ayikwazanga ukuvula izithombe",
        "Please try opening the photo library again.": "Sicela uzame ukuvula ilabhulali yezithombe futhi.",
        "Choose a username": "Khetha igama lomsebenzisi",
        "Your name": "Igama lakho",
        "Tell people about yourself": "Tshela abantu ngawe",
        "City, country": "Idolobha, izwe",
        "Save profile": "Londoloza iphrofayela",
        "Change profile photo": "Shintsha isithombe sephrofayela",
        "Change Photo": "Shintsha isithombe",
        "JPG, PNG up to 5MB": "JPG, PNG kufika ku-5MB",
        "This is how people find you on nook.": "Yile ndlela abantu abakuthola ngayo ku-nook.",
        "Display Name": "Igama eliboniswa emphakathini",
        "This is your public name.": "Leli igama lakho elibonwa umphakathi.",
        "Share your first moment, or discover people to follow.": "Yabelana ngomzuzu wakho wokuqala, noma uthole abantu ongabalandela.",
        "Unread": "Engafundiwe",
        "Groups": "Amaqembu",
        "For now, start a private conversation with one member.": "Okwamanje, qala ingxoxo eyimfihlo nelungu elilodwa.",
        "You’re all caught up": "Usufinyelele emilayezweni yakamuva",
        "You don’t have any unread messages.": "Awunayo imilayezo engafundiwe.",
        "Start a conversation with someone in the community.": "Qala ingxoxo nomuntu othile emphakathini.",
        "We couldn’t open this conversation. Check your connection and that you’re signed in with the right account.": "Asikwazanga ukuvula le ngxoxo. Hlola uxhumano lwakho nokuthi ungene nge-akhawunti efanele.",
        "Search Explore": "Sesha ku-Hlola",
        "No posts found. Try another search or topic.": "Akukho okuthunyelwe okutholakele. Zama olunye usesho noma isihloko.",
        "Search people, posts, or topics": "Sesha abantu, okuthunyelwe noma izihloko",
        "Suggested for you": "Okuphakanyiselwe wena",
        "See all suggested people": "Bona bonke abantu abaphakanyisiwe",
        "See all": "Bona konke",
        "No suggested people yet.": "Abekho abantu abaphakanyisiwe okwamanje.",
        "Choose a topic": "Khetha isihloko",
        "Open": "Vula",
        "View": "Buka",
        "Options for": "Izinketho ze-",
        "topic": "isihloko",
        "All": "Konke",
        "Travel": "Ukuhamba",
        "Nature": "Imvelo",
        "Pets": "Izilwane ezifuywayo",
        "Food": "Ukudla",
        "Design": "Idizayini",
        "Lifestyle": "Indlela yokuphila",
        "Open post": "Vula okuthunyelwe",
        "Post options": "Izinketho zokuthunyelwe",
        "Unlike post": "Yeka ukuthanda okuthunyelwe",
        "Like post": "Thanda okuthunyelwe",
        "View comments": "Buka amazwana",
        "Add your story": "Engeza indaba yakho",
        "Story": "Indaba",
        "More story options": "Ezinye izinketho zendaba",
        "Previous story": "Indaba edlule",
        "Next story": "Indaba elandelayo",
        "Finishing publication": "Kuqedelwa ukushicilela",
        "Keep this screen open while the server confirms your": "Gcina lesi sikrini sivuliwe ngenkathi iseva iqinisekisa",
        "Cancel upload?": "Khansela ukulayisha?",
        "Your unfinished upload will be discarded.": "Ukulayisha kwakho okungakaqedwa kuzolahlwa.",
        "Your unfinished upload and caption will be discarded.": "Ukulayisha kwakho okungakaqedwa namazwibela kuzolahlwa.",
        "Keep uploading": "Qhubeka nokulayisha",
        "Cancel upload": "Khansela ukulayisha",
        "Discard story?": "Lahla indaba?",
        "Discard post?": "Lahla okuthunyelwe?",
        "Your selected photo will be discarded.": "Isithombe osikhethile sizolahlwa.",
        "Your selected media and caption will be discarded.": "Imidiya namazwibela okukhethile kuzolahlwa.",
        "Your text post will be discarded.": "Okuthunyelwe kwakho kombhalo kuzolahlwa.",
        "Close composer": "Vala umhleli wokuthunyelwe",
        "New story": "Indaba entsha",
        "New post": "Okuthunyelwe okusha",
        "Share post": "Yabelana ngokuthunyelwe",
        "Posting…": "Kuyathunyelwa…",
        "Select a photo for your story": "Khetha isithombe sendaba yakho",
        "Select a photo or video for your post": "Khetha isithombe noma ividiyo yokuthunyelwe kwakho",
        "Change media": "Shintsha imidiya",
        "Add media": "Engeza imidiya",
        "Media": "Imidiya",
        "Opening…": "Kuyavulwa…",
        "Change selected media": "Shintsha imidiya ekhethiwe",
        "Selected video": "Ividiyo ekhethiwe",
        "sec": "isekhondi",
        "Post caption": "Amazwibela okuthunyelwe",
        "Uploading": "Kuyalayishwa",
        "Preparing media…": "Kulungiselelwa imidiya…",
        "Delete post?": "Susa lokhu okuthunyelwe?",
        "Send a link to this post": "Thumela isixhumanisi salokhu okuthunyelwe",
        "Remove this post": "Susa lokhu okuthunyelwe",
        "Search people and posts": "Sesha abantu nokuthunyelwe",
        "Close": "Vala",
        "Close post options": "Vala izinketho zokuthunyelwe",
        "This removes the post, its media, likes, and comments.": "Lokhu kususa okuthunyelwe, imidiya yako, ukuthandwa namazwana.",
        "OK": "KULUNGILE",
        "Shares a link that opens this post in nook": "Yabelana ngesixhumanisi esivula lokhu okuthunyelwe ku-nook",
        "Delete comment?": "Susa amazwana?",
        "This comment and its replies will no longer be visible.": "La mazwana nezimpendulo zawo ngeke zisabonakala.",
        "This post may have been deleted.": "Kungenzeka ukuthi lokhu okuthunyelwe kususiwe.",
        "Close story viewers": "Vala ababukeli bendaba",
        "Close story options": "Vala izinketho zendaba",
        "Cancel deleting story": "Khansela ukususa indaba",
        "Dismiss message": "Vala umlayezo",
        "Version": "Inguqulo",
        "Welcome": "Siyakwamukela",
        "Sign in to continue to your account and pick up where you left off.": "Ngena ngemvume ukuze uqhubekele ku-akhawunti yakho futhi uqhubeke lapho ugcine khona.",
        "Signing in…": "Kuyangena ngemvume…",
        "By continuing, you agree to our": "Ngokuqhubeka, uyavumelana ne-",
        "and acknowledge our": "futhi uyavuma",
        "Completing sign in": "Kuqedelwa ukungena ngemvume",
        "Nook": "Nook",
        "Finishing sign in": "Kuqedelwa ukungena ngemvume",
        "Getting things ready": "Kulungiselelwa konke",
        "Your account is being connected securely. This will only take a moment.": "I-akhawunti yakho ixhunywa ngokuphephile. Lokhu kuzothatha isikhashana.",
        "Signing in": "Kuyangena ngemvume",
        "Secure sign-in": "Ukungena ngemvume okuphephile",
        "Newest first": "Okusha kuqala",
        "Oldest first": "Okudala kuqala",
        "Sort comments": "Hlunga amazwana",
        "Newest": "Okusha",
        "Oldest": "Okudala",
        "Close sort menu": "Vala imenyu yokuhlunga",
        "Comment options": "Izinketho zamazwana",
        "Edit or delete your comment": "Hlela noma susa amazwana akho",
        "Close comment options": "Vala izinketho zamazwana",
        "Edit comment": "Hlela amazwana",
        "Delete comment": "Susa amazwana",
        "Unlike comment": "Yeka ukuthanda amazwana",
        "Like comment": "Thanda amazwana",
    },
    fr: {
        "Home": "Accueil",
        "Explore": "Explorer",
        "Messages": "Messages",
        "Profile": "Profil",
        "Settings": "Paramètres",
        "Account": "Compte",
        "Support & Legal": "Aide et informations légales",
        "Edit profile": "Modifier le profil",
        "Saved posts": "Publications enregistrées",
        "Blocked users": "Utilisateurs bloqués",
        "Report a problem": "Signaler un problème",
        "Privacy Policy": "Politique de confidentialité",
        "Terms of Service": "Conditions d’utilisation",
        "About": "À propos",
        "Share feedback": "Envoyer un commentaire",
        "Sign Out": "Se déconnecter",
        "Signing out…": "Déconnexion…",
        "Language": "Langue",
        "Choose the language used in nook.": "Choisissez la langue utilisée dans nook.",
        "English": "Anglais",
        "isiZulu": "isiZulu",
        "Cancel": "Annuler",
        "Save": "Enregistrer",
        "Done": "Terminé",
        "Retry": "Réessayer",
        "Loading…": "Chargement…",
        "Search": "Rechercher",
        "Search people": "Rechercher des personnes",
        "Search posts": "Rechercher des publications",
        "Follow": "Suivre",
        "Following": "Abonné(e)",
        "Followers": "Abonnés",
        "Unfollow": "Ne plus suivre",
        "Message": "Message",
        "Post": "Publication",
        "Posts": "Publications",
        "Videos": "Vidéos",
        "Saved": "Enregistré",
        "Like": "J’aime",
        "Unlike": "Je n’aime plus",
        "Comment": "Commenter",
        "Comments": "Commentaires",
        "Reply": "Répondre",
        "Replies": "Réponses",
        "Share": "Partager",
        "Edit": "Modifier",
        "Delete": "Supprimer",
        "Write a comment…": "Écrire un commentaire…",
        "Write a reply…": "Écrire une réponse…",
        "Send": "Envoyer",
        "Send message": "Envoyer un message",
        "Type a message…": "Écrire un message…",
        "Online": "En ligne",
        "Offline": "Hors ligne",
        "New message": "Nouveau message",
        "No messages yet.": "Aucun message pour le moment.",
        "No posts yet.": "Aucune publication pour le moment.",
        "No videos to show.": "Aucune vidéo à afficher.",
        "No blocked users": "Aucun utilisateur bloqué",
        "Unblock": "Débloquer",
        "Unblocking…": "Déblocage…",
        "Block user": "Bloquer l’utilisateur",
        "Block": "Bloquer",
        "Profile unavailable": "Profil indisponible",
        "Create story": "Créer une story",
        "Your story": "Votre story",
        "Story viewers": "Vues de la story",
        "Pause": "Mettre en pause",
        "Resume": "Reprendre",
        "Share your feedback": "Partagez vos commentaires",
        "What’s on your mind?": "À quoi pensez-vous ?",
        "Send feedback": "Envoyer",
        "Name (optional)": "Nom (facultatif)",
        "Email (optional)": "E-mail (facultatif)",
        "Thanks for helping improve nook!": "Merci de contribuer à l’amélioration de nook !",
        "Edit Profile": "Modifier le profil",
        "Discover people": "Découvrir des personnes",
        "Back to profile": "Retour au profil",
        "Back to settings": "Retour aux paramètres",
        "No saved posts yet.": "Aucune publication enregistrée pour le moment.",
        "When people follow this profile, they’ll appear here.": "Les personnes qui suivent ce profil apparaîtront ici.",
        "The profiles they follow will appear here.": "Les profils suivis apparaîtront ici.",
        "Load more": "Afficher plus",
        "Couldn’t load. Tap to retry.": "Chargement impossible. Touchez pour réessayer.",
        "Something went wrong. Check your connection and try again.": "Une erreur s’est produite. Vérifiez votre connexion et réessayez.",
        "You’ve blocked this account. Unblock them to see their posts and interact again.": "Vous avez bloqué ce compte. Débloquez-le pour voir ses publications et interagir à nouveau.",
        "No one here yet.": "Personne pour le moment.",
        "Tap to resume": "Touchez pour reprendre",
        "Edit story": "Modifier la story",
        "Delete story": "Supprimer la story",
        "Keep story": "Conserver la story",
        "Story unavailable": "Story indisponible",
        "This story is no longer available.": "Cette story n’est plus disponible.",
        "What would you like to share?": "Que souhaitez-vous partager ?",
        "Add a caption…": "Ajouter une légende…",
        "Publish": "Publier",
        "Publishing…": "Publication…",
        "Discard": "Abandonner",
        "Discard changes?": "Abandonner les modifications ?",
        "Edit post": "Modifier la publication",
        "Save changes": "Enregistrer les modifications",
        "Saving…": "Enregistrement…",
        "Could not load your profile": "Impossible de charger votre profil",
        "Your profile": "Votre profil",
        "Username": "Nom d’utilisateur",
        "Name": "Nom",
        "Bio": "Bio",
        "Website": "Site web",
        "Location": "Lieu",
        "Photo": "Photo",
        "Camera": "Appareil photo",
        "No conversations yet.": "Aucune conversation pour le moment.",
        "Message requests": "Demandes de message",
        "Accept": "Accepter",
        "Decline": "Refuser",
        "Today": "Aujourd’hui",
        "Yesterday": "Hier",
        "Active now": "Actif maintenant",
        "Last seen": "Vu(e) pour la dernière fois",
        "Unknown": "Inconnu",
        "Search nook": "Rechercher sur nook",
        "People": "Personnes",
        "For you": "Pour vous",
        "Recent": "Récent",
        "Clear": "Effacer",
        "No results found.": "Aucun résultat trouvé.",
        "Signed in as": "Connecté(e) en tant que",
        "Could not change language": "Impossible de changer de langue",
        "Please try again.": "Veuillez réessayer.",
        "Preview account": "Compte de démonstration",
        "Sign out is available from your live profile.": "Vous pouvez vous déconnecter depuis votre profil actif.",
        "Unable to sign out": "Impossible de se déconnecter",
        "Edit your profile photo": "Modifier votre photo de profil",
        "Go back": "Retour",
        "Tagged": "Identifications",
        "Try again": "Réessayer",
        "Could not unblock user": "Impossible de débloquer cet utilisateur",
        "Couldn’t load your blocked users.": "Impossible de charger les utilisateurs bloqués.",
        "People you block will appear here. You can unblock them at any time.": "Les personnes que vous bloquez apparaîtront ici. Vous pourrez les débloquer à tout moment.",
        "Unblock user": "Débloquer l’utilisateur",
        "Unblock @": "Débloquer @",
        "Continue": "Continuer",
        "Group messaging": "Messages de groupe",
        "Conversation unavailable": "Conversation indisponible",
        "Back to messages": "Retour aux messages",
        "Your feed starts here": "Votre fil d’actualité commence ici",
        "Explore the community": "Découvrir la communauté",
        "story": "story",
        "post": "publication",
        "Keep this screen open while your": "Gardez cet écran ouvert pendant que votre",
        "is being shared.": "est en cours de partage.",
        "Write a caption…": "Écrire une légende…",
        "Share story": "Partager la story",
        "Send a link to this story": "Envoyer un lien vers cette story",
        "Remove it before it expires": "La supprimer avant son expiration",
        "Post unavailable": "Publication indisponible",
        "Media unavailable. Tap to retry.": "Média indisponible. Touchez pour réessayer.",
        "Search people, posts, or topics...": "Rechercher des personnes, publications ou sujets…",
        "Search name or username": "Rechercher un nom ou un nom d’utilisateur",
        "Load earlier messages": "Charger les messages précédents",
        "Could not load reactions": "Impossible de charger les réactions",
        "Could not update message request": "Impossible de mettre à jour la demande de message",
        "Could not react to message": "Impossible de réagir au message",
        "Could not edit message": "Impossible de modifier le message",
        "Could not delete message": "Impossible de supprimer le message",
        "Could not open chat": "Impossible d’ouvrir la conversation",
        "Could not update like": "Impossible de mettre à jour le J’aime",
        "Could not update follow": "Impossible de mettre à jour l’abonnement",
        "Create a post": "Créer une publication",
        "Edited": "Modifié",
        "Sending…": "Envoi…",
        "Delivered": "Distribué",
        "You": "Vous",
        "Dismiss reactions": "Fermer les réactions",
        "Message options": "Options du message",
        "This message will be removed only from your chat.": "Ce message sera supprimé uniquement de votre conversation.",
        "This message will be removed for everyone in the conversation.": "Ce message sera supprimé pour tout le monde dans la conversation.",
        "Close message options": "Fermer les options du message",
        "Delete message?": "Supprimer le message ?",
        "React with": "Réagir avec",
        "Remove": "Supprimer",
        "Cancel editing": "Annuler la modification",
        "Cancel reply": "Annuler la réponse",
        "Decline message request": "Refuser la demande de message",
        "Accept message request": "Accepter la demande de message",
        "Open emoji picker": "Ouvrir le sélecteur d’émojis",
        "No conversations yet": "Aucune conversation pour le moment",
        "Retry sharing": "Réessayer le partage",
        "Opening conversation…": "Ouverture de la conversation…",
        "Couldn’t open conversation": "Impossible d’ouvrir la conversation",
        "Check your connection and try again.": "Vérifiez votre connexion et réessayez.",
        "Search members to message": "Rechercher des membres à qui écrire",
        "Cancel block confirmation": "Annuler la confirmation du blocage",
        "They won’t be able to see your posts or message you. You won’t see their posts, and you’ll both be unfollowed.": "Cette personne ne pourra pas voir vos publications ni vous envoyer de message. Vous ne verrez pas ses publications et vous cesserez mutuellement de vous suivre.",
        "Blocking…": "Blocage…",
        "Saving your profile": "Enregistrement de votre profil",
        "Saving": "Enregistrement",
        "Close reaction details": "Fermer les détails des réactions",
        "Could not share": "Impossible de partager",
        "Could not save bookmark": "Impossible d’enregistrer le favori",
        "Could not delete comment": "Impossible de supprimer le commentaire",
        "Could not save profile": "Impossible d’enregistrer le profil",
        "Could not update": "Impossible de mettre à jour",
        "Check your profile": "Vérifiez votre profil",
        "Your unsaved profile changes will be lost.": "Les modifications non enregistrées de votre profil seront perdues.",
        "Keep editing": "Continuer la modification",
        "Choose a JPG or PNG": "Choisissez un fichier JPG ou PNG",
        "Please select a JPG or PNG image for your profile photo.": "Veuillez sélectionner une image JPG ou PNG pour votre photo de profil.",
        "Choose a smaller photo": "Choisissez une photo plus petite",
        "Select an image with a known size of 5 MB or less.": "Sélectionnez une image dont la taille est connue et inférieure ou égale à 5 Mo.",
        "Unable to open photos": "Impossible d’ouvrir les photos",
        "Please try opening the photo library again.": "Veuillez réessayer d’ouvrir la photothèque.",
        "Choose a username": "Choisissez un nom d’utilisateur",
        "Your name": "Votre nom",
        "Tell people about yourself": "Parlez de vous",
        "City, country": "Ville, pays",
        "Save profile": "Enregistrer le profil",
        "Change profile photo": "Modifier la photo de profil",
        "Change Photo": "Modifier la photo",
        "JPG, PNG up to 5MB": "JPG ou PNG, jusqu’à 5 Mo",
        "This is how people find you on nook.": "C’est ainsi que les autres vous trouvent sur nook.",
        "Display Name": "Nom affiché",
        "This is your public name.": "C’est votre nom public.",
        "Share your first moment, or discover people to follow.": "Partagez votre premier moment ou découvrez des personnes à suivre.",
        "Unread": "Non lus",
        "Groups": "Groupes",
        "For now, start a private conversation with one member.": "Pour le moment, démarrez une conversation privée avec un membre.",
        "You’re all caught up": "Vous êtes à jour",
        "You don’t have any unread messages.": "Vous n’avez aucun message non lu.",
        "Start a conversation with someone in the community.": "Commencez une conversation avec un membre de la communauté.",
        "We couldn’t open this conversation. Check your connection and that you’re signed in with the right account.": "Impossible d’ouvrir cette conversation. Vérifiez votre connexion et que vous utilisez le bon compte.",
        "Search Explore": "Rechercher dans Explorer",
        "No posts found. Try another search or topic.": "Aucune publication trouvée. Essayez une autre recherche ou un autre sujet.",
        "Search people, posts, or topics": "Rechercher des personnes, publications ou sujets",
        "Suggested for you": "Suggestions pour vous",
        "See all suggested people": "Voir toutes les personnes suggérées",
        "See all": "Tout voir",
        "No suggested people yet.": "Aucune suggestion de personne pour le moment.",
        "Choose a topic": "Choisir un sujet",
        "Open": "Ouvrir",
        "View": "Voir",
        "Options for": "Options pour",
        "topic": "sujet",
        "All": "Tout",
        "Travel": "Voyage",
        "Nature": "Nature",
        "Pets": "Animaux",
        "Food": "Cuisine",
        "Design": "Design",
        "Lifestyle": "Mode de vie",
        "Open post": "Ouvrir la publication",
        "Post options": "Options de la publication",
        "Unlike post": "Retirer le J’aime",
        "Like post": "Aimer la publication",
        "View comments": "Voir les commentaires",
        "Add your story": "Ajouter votre story",
        "Story": "Story",
        "More story options": "Plus d’options pour la story",
        "Previous story": "Story précédente",
        "Next story": "Story suivante",
        "Finishing publication": "Finalisation de la publication",
        "Keep this screen open while the server confirms your": "Gardez cet écran ouvert pendant que le serveur confirme votre",
        "Cancel upload?": "Annuler l’envoi ?",
        "Your unfinished upload will be discarded.": "Votre envoi inachevé sera abandonné.",
        "Your unfinished upload and caption will be discarded.": "Votre envoi inachevé et sa légende seront abandonnés.",
        "Keep uploading": "Continuer l’envoi",
        "Cancel upload": "Annuler l’envoi",
        "Discard story?": "Abandonner la story ?",
        "Discard post?": "Abandonner la publication ?",
        "Your selected photo will be discarded.": "La photo sélectionnée sera abandonnée.",
        "Your selected media and caption will be discarded.": "Le média sélectionné et sa légende seront abandonnés.",
        "Your text post will be discarded.": "Votre publication textuelle sera abandonnée.",
        "Close composer": "Fermer l’éditeur",
        "New story": "Nouvelle story",
        "New post": "Nouvelle publication",
        "Share post": "Partager la publication",
        "Posting…": "Publication…",
        "Select a photo for your story": "Sélectionner une photo pour votre story",
        "Select a photo or video for your post": "Sélectionner une photo ou une vidéo pour votre publication",
        "Change media": "Modifier le média",
        "Add media": "Ajouter un média",
        "Media": "Média",
        "Opening…": "Ouverture…",
        "Change selected media": "Modifier le média sélectionné",
        "Selected video": "Vidéo sélectionnée",
        "sec": "s",
        "Post caption": "Légende de la publication",
        "Uploading": "Envoi en cours",
        "Preparing media…": "Préparation du média…",
        "Delete post?": "Supprimer la publication ?",
        "Send a link to this post": "Envoyer un lien vers cette publication",
        "Remove this post": "Supprimer cette publication",
        "Search people and posts": "Rechercher des personnes et des publications",
        "Close": "Fermer",
        "Close post options": "Fermer les options de la publication",
        "This removes the post, its media, likes, and comments.": "La publication, ses médias, ses mentions J’aime et ses commentaires seront supprimés.",
        "OK": "OK",
        "Shares a link that opens this post in nook": "Partage un lien qui ouvre cette publication dans nook",
        "Delete comment?": "Supprimer le commentaire ?",
        "This comment and its replies will no longer be visible.": "Ce commentaire et ses réponses ne seront plus visibles.",
        "This post may have been deleted.": "Cette publication a peut-être été supprimée.",
        "Close story viewers": "Fermer la liste des vues de la story",
        "Close story options": "Fermer les options de la story",
        "Cancel deleting story": "Annuler la suppression de la story",
        "Dismiss message": "Fermer le message",
        "Version": "Version",
        "Welcome": "Bienvenue",
        "Sign in to continue to your account and pick up where you left off.": "Connectez-vous à votre compte pour reprendre là où vous en étiez.",
        "Signing in…": "Connexion…",
        "By continuing, you agree to our": "En continuant, vous acceptez nos",
        "and acknowledge our": "et reconnaissez notre",
        "Completing sign in": "Finalisation de la connexion",
        "Nook": "Nook",
        "Finishing sign in": "Finalisation de la connexion",
        "Getting things ready": "Préparation en cours",
        "Your account is being connected securely. This will only take a moment.": "Votre compte est connecté de manière sécurisée. Cela ne prendra qu’un instant.",
        "Signing in": "Connexion",
        "Secure sign-in": "Connexion sécurisée",
        "Newest first": "Plus récents d’abord",
        "Oldest first": "Plus anciens d’abord",
        "Sort comments": "Trier les commentaires",
        "Newest": "Plus récents",
        "Oldest": "Plus anciens",
        "Close sort menu": "Fermer le menu de tri",
        "Comment options": "Options du commentaire",
        "Edit or delete your comment": "Modifier ou supprimer votre commentaire",
        "Close comment options": "Fermer les options du commentaire",
        "Edit comment": "Modifier le commentaire",
        "Delete comment": "Supprimer le commentaire",
        "Unlike comment": "Retirer le J’aime du commentaire",
        "Like comment": "Aimer le commentaire",
    },
};

async function readStoredLanguage(): Promise<NookLanguage | null> {
    try {
        const value = Platform.OS === "web"
            ? typeof localStorage === "undefined"
                ? null
                : localStorage.getItem(STORAGE_KEY)
            : await SecureStore.getItemAsync(STORAGE_KEY);
        return value === "en" || value === "zu" || value === "fr" ? value : null;
    } catch (error) {
        console.warn("Unable to read saved language preference.", error);
        return null;
    }
}

async function saveStoredLanguage(language: NookLanguage) {
    if (Platform.OS === "web") {
        if (typeof localStorage === "undefined") {
            throw new Error("Language preference storage is unavailable.");
        }
        localStorage.setItem(STORAGE_KEY, language);
        return;
    }
    await SecureStore.setItemAsync(STORAGE_KEY, language);
}

type LanguageContextValue = {
    language: NookLanguage;
    isLanguageLoaded: boolean;
    setLanguage: (language: NookLanguage) => Promise<void>;
    t: (text: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<NookLanguage>("en");
    const [isLanguageLoaded, setIsLanguageLoaded] = useState(false);

    useEffect(() => {
        let active = true;
        void readStoredLanguage().then(saved => {
            if (active && saved) setLanguageState(saved);
            if (active) setIsLanguageLoaded(true);
        });
        return () => {
            active = false;
        };
    }, []);

    const setLanguage = useCallback(async (next: NookLanguage) => {
        await saveStoredLanguage(next);
        setLanguageState(next);
    }, []);

    const value = useMemo<LanguageContextValue>(() => ({
        language,
        isLanguageLoaded,
        setLanguage,
        t: (text: string) => translations[language][text] ?? text,
    }), [isLanguageLoaded, language, setLanguage]);

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useNookLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useNookLanguage must be used inside LanguageProvider.");
    }
    return context;
}
